Some Propensity Ideas and the Right Heart Catheterization Data
================
Thomas E. Love, Ph.D.
2019-03-14

  - [Preliminaries](#preliminaries)
      - [Study Background](#study-background)
      - [Loading Packages](#loading-packages)
      - [Importing the Data](#importing-the-data)
      - [The Data Set after Initial
        Import](#the-data-set-after-initial-import)
      - [Any missingness?](#any-missingness)
  - [The Treatment / Exposure We’ll
    Study](#the-treatment-exposure-well-study)
  - [The 3 Outcomes We’ll Study](#the-3-outcomes-well-study)
      - [Mortality, a binary outcome:
        `death`](#mortality-a-binary-outcome-death)
      - [Working with Dates to Define the Time-Related
        Outcomes](#working-with-dates-to-define-the-time-related-outcomes)
          - [The Raw Data on Dates](#the-raw-data-on-dates)
          - [Impute hospital discharge date for the one missing
            value](#impute-hospital-discharge-date-for-the-one-missing-value)
      - [Length of initial hospital stay, a quantitative outcome:
        `hospdays`](#length-of-initial-hospital-stay-a-quantitative-outcome-hospdays)
      - [Survival Time in Days, a time-to-event outcome:
        `survdays`](#survival-time-in-days-a-time-to-event-outcome-survdays)
  - [The 50 Covariates We’ll Study](#the-50-covariates-well-study)
      - [Group 1: Socio-demographics (6
        covariates)](#group-1-socio-demographics-6-covariates)
      - [Group 2: Presentation at Admission (7
        covariates)](#group-2-presentation-at-admission-7-covariates)
      - [Group 3: Admission Diagnosis Categories (10
        covariates)](#group-3-admission-diagnosis-categories-10-covariates)
      - [Group 4: Comorbid Illness and Transfer Status (13
        covariates)](#group-4-comorbid-illness-and-transfer-status-13-covariates)
      - [Group 5: Day 1 Summary Measures of Presentation / Severity of
        Illness (4
        covariates)](#group-5-day-1-summary-measures-of-presentation-severity-of-illness-4-covariates)
      - [Group 6: Day 1 Lab Results (10
        covariates)](#group-6-day-1-lab-results-10-covariates)
  - [A Little Refactoring](#a-little-refactoring)
      - [Saving the Data File](#saving-the-data-file)
  - [Unadjusted Outcome Assessments](#unadjusted-outcome-assessments)
      - [Outcome A: In-Study Mortality
        (binary)](#outcome-a-in-study-mortality-binary)
          - [Fitting the Model with the 1/0 treatment and
            outcome](#fitting-the-model-with-the-10-treatment-and-outcome)
          - [Fitting the Model with the treatment and outcome as factors
            requires
            care](#fitting-the-model-with-the-treatment-and-outcome-as-factors-requires-care)
      - [Outcome B: Length of Stay
        (quantitative)](#outcome-b-length-of-stay-quantitative)
      - [Outcome C: Time to death
        (time-to-event)](#outcome-c-time-to-death-time-to-event)
  - [Estimate the Propensity Score with Logistic
    Regression](#estimate-the-propensity-score-with-logistic-regression)
      - [Store the propensity scores and linear propensity
        scores](#store-the-propensity-scores-and-linear-propensity-scores)
      - [Plot the Propensity Scores to Verify that they Match Your
        Expectations](#plot-the-propensity-scores-to-verify-that-they-match-your-expectations)
  - [Checking Rubin’s Rules Prior to Propensity
    Adjustment](#checking-rubins-rules-prior-to-propensity-adjustment)
  - [Match 1: 1:1 Greedy Matching on the linear PS, without
    Replacement](#match-1-11-greedy-matching-on-the-linear-ps-without-replacement)
      - [Love Plot for Match 1](#love-plot-for-match-1)
      - [Rubin’s Rules 1 and 2 for Match
        1](#rubins-rules-1-and-2-for-match-1)
  - [Match 2: 1:2 Greedy Matching on the linear PS, without
    Replacement](#match-2-12-greedy-matching-on-the-linear-ps-without-replacement)
      - [Love Plot for Match 2](#love-plot-for-match-2)
      - [Rubin’s Rules 1 and 2 for Match
        2](#rubins-rules-1-and-2-for-match-2)
  - [Match 3: Genetic Search Matching to do 1:1 Matching without
    replacement](#match-3-genetic-search-matching-to-do-11-matching-without-replacement)
      - [Love Plot for Match 3](#love-plot-for-match-3)
      - [Rubin’s Rules 1 and 2 for Match
        3](#rubins-rules-1-and-2-for-match-3)
  - [Match 4: 1:1 Greedy Matching on the linear PS, WITH
    Replacement](#match-4-11-greedy-matching-on-the-linear-ps-with-replacement)
      - [Love Plot for Match 4](#love-plot-for-match-4)
      - [Rubin’s Rules 1 and 2 for Match
        4](#rubins-rules-1-and-2-for-match-4)
  - [Match 5: 1:1 Caliper Matching on the linear PS, WITH
    Replacement](#match-5-11-caliper-matching-on-the-linear-ps-with-replacement)
      - [Love Plot for Match 5](#love-plot-for-match-5)
      - [Rubin’s Rules 1 and 2 for Match
        5](#rubins-rules-1-and-2-for-match-5)
  - [Match 6: 1:2 Greedy Matching on the linear PS, WITH
    Replacement](#match-6-12-greedy-matching-on-the-linear-ps-with-replacement)
      - [Love Plot for Match 6](#love-plot-for-match-6)
      - [Rubin’s Rules 1 and 2 for Match
        6](#rubins-rules-1-and-2-for-match-6)
  - [Ranking the Matches](#ranking-the-matches)
  - [ATT Matching Estimates for the Binary Outcome,
    Death](#att-matching-estimates-for-the-binary-outcome-death)
      - [With Match 1, in detail](#with-match-1-in-detail)
      - [With Matches 2-6, in much less
        detail](#with-matches-2-6-in-much-less-detail)
      - [Graphing the Results Across Multiple Matching
        Strategies](#graphing-the-results-across-multiple-matching-strategies)
  - [ATT Matching Estimates for the Quantitative Outcome, Hospital
    Length of
    Stay](#att-matching-estimates-for-the-quantitative-outcome-hospital-length-of-stay)
      - [With Match 1, in detail](#with-match-1-in-detail-1)
      - [With Matches 2-6, in much less
        detail](#with-matches-2-6-in-much-less-detail-1)
      - [Graphing the Results Across Multiple Matching
        Strategies](#graphing-the-results-across-multiple-matching-strategies-1)
  - [ATT Matching Estimates for the Time-to-Event Outcome, In-Study
    Survival](#att-matching-estimates-for-the-time-to-event-outcome-in-study-survival)
      - [With Match 1, in detail](#with-match-1-in-detail-2)
      - [With Matches 2-6, in much less
        detail](#with-matches-2-6-in-much-less-detail-2)
      - [Graphing the Results Across Multiple Matching
        Strategies](#graphing-the-results-across-multiple-matching-strategies-2)
  - [Sensitivity Analyses](#sensitivity-analyses)
      - [For the Binary Outcome, Death](#for-the-binary-outcome-death)
      - [For the Quantitative Outcome, In-Hospital Length of
        Stay](#for-the-quantitative-outcome-in-hospital-length-of-stay)
      - [For the Survival Outcome, In-Study Time to
        Death](#for-the-survival-outcome-in-study-time-to-death)
  - [Session Info](#session-info)

# Preliminaries

## Study Background

This example is based on the Right Heart Catheterization data set
available at [Vanderbilt
University](http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets) and
described
[here](http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/rhc.html).
The key reference is Connors AF et al. 1996 The effectiveness of RHC in
the initial care of critically ill patients. [*JAMA* 276:
889-897](http://jamanetwork.com/journals/jama/fullarticle/407990).
Connors et al. used a logistic regression model to develop a propensity
score then: \[a\] matched RHC to non-RHC patients and \[b\] adjusted for
propensity score in models for outcomes, followed by a sensitivity
analysis. The key conclusions were that RHC patients had decreased
survival time, and any unmeasured confounder would have to be somewhat
strong to explain away the results.

## Loading Packages

``` r
library(here); library(janitor); library(naniar)
library(tableone); library(broom); library(survival)
library(Matching); library(cobalt); library(rgenoud)
library(lme4); library(rbounds)
library(tidyverse)
```

## Importing the Data

The observations in the `rhc` data set describe 5,735 subjects who are
critically ill, and most variables were obtained during day 1 of a
hospitalization. We’ll begin by importing the `rhc` data into a
**tibble** (a lazy and surly data frame - see R’s help file on tibbles
for more details) in R that contains 5,735 observations (rows) on 63
variables (columns).

In the import process, we’re going to do a few things to simplify the
process of getting a functional data set.

  - The automated column specification in R’s **readr** package uses the
    first 1000 rows of the data set - with the `rhc` data, this creates
    parsing failures for several measures which are assumed to be
    integers but actually should be parsed as doubles (continuous
    variables). So we specify the column types for those variables here
    then allow R to identify the type for the other columns.
  - By default, **readr**’s `read_csv` command treats all string
    variables as characters, and not as factors. For several
    multicategorical variables, we want a factor representation in a
    specific order, so we’ll specify that, too, also using the `cols`
    function.

<!-- end list -->

``` r
column_types_rhc <- 
    cols(urin1 = "d", meanbp1 = "d", resp1 = "d",
    swang1 = col_factor(c("RHC", "No RHC")),
    death = col_factor(c("No", "Yes")),
    sex = col_factor(c("Male", "Female")),
    cat1 = col_factor(c("ARF", "CHF", "Cirrhosis", "Colon Cancer", "Coma", "COPD",
                        "Lung Cancer", "MOSF w/Malignancy", "MOSF w/Sepsis")),
    dnr1 = col_factor(c("No", "Yes")),
    card = col_factor(c("No", "Yes")),
    gastr = col_factor(c("No", "Yes")),
    hema = col_factor(c("No", "Yes")),
    meta = col_factor(c("No", "Yes")),
    neuro = col_factor(c("No", "Yes")),
    ortho = col_factor(c("No", "Yes")),
    renal = col_factor(c("No", "Yes")),
    resp = col_factor(c("No", "Yes")),
    seps = col_factor(c("No", "Yes")),
    trauma = col_factor(c("No", "Yes")),
    income = col_factor(c("Under $11k", "$11-$25k", "$25-$50k", "> $50k")),
    ninsclas = col_factor(c("Private", "Private & Medicare", "Medicare", 
                             "Medicare & Medicaid", "Medicaid", "No insurance")),
    race = col_factor(c("white", "black", "other")),
    ca = col_factor(c("No", "Yes", "Metastatic"))
)

rhc_raw <- read_csv("http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/rhc.csv", 
                    col_types = column_types_rhc)
```

    Warning: Missing column names filled in: 'X1' [1]

  - After we import the data, we re-order the columns to present the
    SUPPORT patient identification code first, then the exposure
    (`swang1`), then information on the outcomes, then information on
    the covariates of interest for our work, dropping the other
    variables.

<!-- end list -->

``` r
rhc_cleaning <- rhc_raw %>% 
    select(ptid, swang1, 
           death, sadmdte, dschdte, dthdte, lstctdte,
           age, sex, edu, income, ninsclas, race,
           cat1, dnr1, wtkilo1, hrt1, meanbp1, resp1, temp1,
           card, gastr, hema, meta, neuro, ortho, renal, 
           resp, seps, trauma,
           amihx, ca, cardiohx, chfhx, chrpulhx, dementhx, 
           gibledhx, immunhx, liverhx, malighx, psychhx, 
           renalhx, transhx, aps1, das2d3pc, scoma1, 
           surv2md1, alb1, bili1, crea1, hema1, paco21, 
           pafi1, ph1, pot1, sod1, wblc1)
```

## The Data Set after Initial Import

The `rhc_cleaning` data at this stage is a tibble (a lazy and surly data
frame) containing 5735 observations (rows) on 57 variables (columns).
The observations describe subjects who are critically ill, and most
variables were obtained during day 1 of a hospitalization.

``` r
rhc_cleaning
```

    # A tibble: 5,735 x 57
       ptid  swang1 death sadmdte dschdte dthdte lstctdte   age sex     edu
       <chr> <fct>  <fct>   <dbl>   <dbl>  <dbl>    <dbl> <dbl> <fct> <dbl>
     1 00005 No RHC No      11142   11151     NA    11382  70.3 Male  12   
     2 00007 RHC    Yes     11799   11844  11844    11844  78.2 Fema~ 12   
     3 00009 RHC    No      12083   12143     NA    12400  46.1 Fema~ 14.1 
     4 00010 No RHC Yes     11146   11183  11183    11182  75.3 Fema~  9   
     5 00011 RHC    Yes     12035   12037  12037    12036  67.9 Male   9.95
     6 00012 No RHC No      12389   12396     NA    12590  86.1 Fema~  8   
     7 00013 No RHC No      12381   12423     NA    12616  55.0 Male  14   
     8 00014 No RHC Yes     11453   11487  11491    11490  43.6 Male  12   
     9 00016 No RHC No      12426   12437     NA    12560  18.0 Fema~ 12.8 
    10 00017 RHC    No      11381   11400     NA    11590  48.4 Fema~ 11.0 
    # ... with 5,725 more rows, and 47 more variables: income <fct>,
    #   ninsclas <fct>, race <fct>, cat1 <fct>, dnr1 <fct>, wtkilo1 <dbl>,
    #   hrt1 <dbl>, meanbp1 <dbl>, resp1 <dbl>, temp1 <dbl>, card <fct>,
    #   gastr <fct>, hema <fct>, meta <fct>, neuro <fct>, ortho <fct>,
    #   renal <fct>, resp <fct>, seps <fct>, trauma <fct>, amihx <dbl>,
    #   ca <fct>, cardiohx <dbl>, chfhx <dbl>, chrpulhx <dbl>, dementhx <dbl>,
    #   gibledhx <dbl>, immunhx <dbl>, liverhx <dbl>, malighx <dbl>,
    #   psychhx <dbl>, renalhx <dbl>, transhx <dbl>, aps1 <dbl>,
    #   das2d3pc <dbl>, scoma1 <dbl>, surv2md1 <dbl>, alb1 <dbl>, bili1 <dbl>,
    #   crea1 <dbl>, hema1 <dbl>, paco21 <dbl>, pafi1 <dbl>, ph1 <dbl>,
    #   pot1 <dbl>, sod1 <dbl>, wblc1 <dbl>

## Any missingness?

``` r
rhc_cleaning %>%
    miss_var_summary()
```

    # A tibble: 57 x 3
       variable n_miss pct_miss
       <chr>     <int>    <dbl>
     1 dthdte     2013  35.1   
     2 dschdte       1   0.0174
     3 ptid          0   0     
     4 swang1        0   0     
     5 death         0   0     
     6 sadmdte       0   0     
     7 lstctdte      0   0     
     8 age           0   0     
     9 sex           0   0     
    10 edu           0   0     
    # ... with 47 more rows

We could also graph this with `gg_miss_var(rhc_cleaning)`. As it turns
out, there were three variables in the raw `rhc` data that have missing
values, but we’ve omitted one (about day 1 urine output) in creating
this `rhc_cleaning` file. The remaining two are dates, and we’ll address
those in the material on creating our outcomes.

# The Treatment / Exposure We’ll Study

The treatment/exposure we are studying is the presence of a Swan-Ganz
(right heart) catheter on day 1, captured in the variable `swang1`. The
Medline Plus description of right heart catheterization [is
here](https://medlineplus.gov/ency/article/003870.htm). Basically, the
procedure passes a thin tube into the right side of the heart and the
arteries leading to the lungs, to measure the heart’s function and blood
flow. It’s done in very ill patients for several reasons, and is also
referred to as right heart catheterization and pulmonary artery
catheterization.

``` r
rhc_cleaning %>% tabyl(swang1)
```

``` 
 swang1    n   percent
    RHC 2184 0.3808195
 No RHC 3551 0.6191805
```

Of course, the most important issue to us is that each subject was not
randomly allocated to either the “RHC” or “No RHC” group. Instead, this
is an **observational** study, where each subject received their
treatment (RHC or no) on the basis of what their providers thought would
be best for them.

# The 3 Outcomes We’ll Study

We will define three outcomes here: one binary, one quantitative, and
one time-to-event.

  - Our first outcome is in-study mortality, captured as a binary
    variable.
  - We will then define hospital length of stay, a quantitative
    variable, and then
  - Time to death, a time-to-event variable that will be right-censored
    for those who did not die during the study.

## Mortality, a binary outcome: `death`

One outcome is death during the study, as captured in the `death`
variable. This is a **binary** outcome.

``` r
rhc_cleaning %>% tabyl(death)
```

``` 
 death    n   percent
    No 2013 0.3510026
   Yes 3722 0.6489974
```

Those people without a value for `dthdte` turn out to be the people with
`death` values of “No” and this makes sense, because `dthdte` is a code
for date of
death.

## Working with Dates to Define the Time-Related Outcomes

### The Raw Data on Dates

| Variable   | Definition              | Values                                                                                                                                                                                                            |
| ---------- | ----------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `sadmdte`  | Study Admission Date    | Integer ranging from 10754 to 12441, indicating the \# of days after 1960-01-01, so study admission date range is actually 1989-06-11 to 1994-01-23.                                                              |
| `dschdte`  | Hospital Discharge Date | Integer ranging from 10757 to 12560, indicating the \# of days after 1960-01-01, so hospital discharge date range is actually 1989-06-14 to 1994-05-22. (**Note: 1 missing value**)                               |
| `dthdte`   | Death Date              | Integer ranging from 10757 to 12783, indicating the \# of days after 1960-01-01, so death date range is actually 1989-06-14 to 1994-12-31. The **2013 people with missing values** are those with No for `death`. |
| `lstctdte` | Date of Last Contact    | Integer ranging from 10756 to 12644, indicating the \# of days after 1960-01-01, so death date range is actually 1989-06-13 to 1994-08-14.                                                                        |

Next, we will develop the two other primary outcomes: survival time
(which we’ll store in `survdays`), and hospital length of stay (which
will go in `hospdays`).

  - It turns out that for three subjects, their dates of last contact
    appear to occur after their death dates, which is irritating, but
    doesn’t affect us much since the only way in which we’ll use the
    last contact date is for calculating survival time for patients
    *without* a death date.

### Impute hospital discharge date for the one missing value

We could just impute a random value, but that’s not a great idea, since
hospital discharge date is tied to other information that is available
to us for this patient. The subject with a missing hospital discharge
date turns out to be `ptid` 08382.

``` r
rhc_cleaning %>% filter(is.na(dschdte)) %>% 
    select(ptid, death, sadmdte, dschdte, dthdte, lstctdte)
```

    # A tibble: 1 x 6
      ptid  death sadmdte dschdte dthdte lstctdte
      <chr> <fct>   <dbl>   <dbl>  <dbl>    <dbl>
    1 08382 Yes     12386      NA  12780    12582

So the patient was admitted to the study on day 12386, had their last
contact with the study on day 12582 (i.e. 196 days after study entry),
and died on day 12780 (i.e. 394 days after study entry.) It seems
rational to impute a value of hospital discharge date that falls in
between their date of study admission and their date of last contact.

  - Among the RHC patients, what is a reasonable guess as to the time
    from study admission to hospital discharge that we might apply to
    this patient? We could see what the distribution of these
    differences are in the available data, like so…

<!-- end list -->

``` r
mosaic::favstats(dschdte - sadmdte ~ swang1, data = rhc_cleaning)
```

``` 
  swang1 min Q1 median Q3 max     mean       sd    n missing
1    RHC   2  8     16 31 342 24.69125 27.80502 2183       1
2 No RHC   2  7     12 22 338 19.52915 23.58672 3551       0
```

I’ll arbitrarily choose to impute a discharge date for `ptid` 08382 so
as to yield a 25 day hospitalization, so as to affect the mean stay
length within the RHC group as little as possible.

This implies that we’ll impute a value of 12386 + 25 = 12411 for this
patient.

``` r
rhc_cleaning <- rhc_cleaning %>%
    mutate(dschdte = replace_na(dschdte, 12411))

rhc_cleaning %>% select(dschdte) %>% miss_var_summary()
```

    # A tibble: 1 x 3
      variable n_miss pct_miss
      <chr>     <int>    <dbl>
    1 dschdte       0        0

## Length of initial hospital stay, a quantitative outcome: `hospdays`

Our third outcome is length of initial hospital stay, which is captured
by subtracting the study admission date (`sadmdte`) from the hospital
discharge date (`dschdte`). This is a **quantitative** outcomes, and we
will create it soon, and name it `hospdays` in our data set.

``` r
rhc_cleaning <- rhc_cleaning %>%
    mutate(hospdays = dschdte - sadmdte)

mosaic::favstats(hospdays ~ swang1, data = rhc_cleaning)
```

``` 
  swang1 min Q1 median Q3 max     mean       sd    n missing
1    RHC   2  8     16 31 342 24.69139 27.79865 2184       0
2 No RHC   2  7     12 22 338 19.52915 23.58672 3551       0
```

It looks like all of these values are reasonable (in that they are all
positive) and we have no missing values.

## Survival Time in Days, a time-to-event outcome: `survdays`

Another outcome is survival time in days (which is censored for all
patients who did not die during the study), and which is captured by
subtracting the study admission date (`sadmdte`) from the death date
(`dthdte`) for the patients who died in study, and the study admission
date (`sadmdte`) from the date of last contact (`lstctdte`) for the
patients who did not die in study. This is a **time-to-event** outcome,
and we will create it soon, and name it `survdays` in our data set.

  - For the subjects who died, this is straightforward, in that we take
    the death date and subtract the study admission date.
  - For those who survived through the study, we take the date of last
    contact and subtract the study admission date, in order to get their
    (right censored) survival times.

<!-- end list -->

``` r
rhc_cleaning <- rhc_cleaning %>%
    mutate(survdays = ifelse(death == "Yes", 
                             dschdte - sadmdte,
                             lstctdte - sadmdte))

mosaic::favstats(survdays ~ death, data = rhc_cleaning)
```

``` 
  death min  Q1 median  Q3  max      mean        sd    n missing
1    No   2 187    210 236 1351 231.18082 112.24989 2013       0
2   Yes   2   6     12  23  338  19.99893  24.59443 3722       0
```

Again, this looks reasonable. All of these values are strictly positive,
for instance, and none seem wildly out of line, and we have no missing
values. We also see that those who died had much shorter survival times
(typically) than those who survived, which makes sense.

We might also look at the `survdays` variable broken down by RHC status.

``` r
mosaic::favstats(survdays ~ swang1, data = rhc_cleaning)
```

``` 
  swang1 min Q1 median  Q3  max     mean       sd    n missing
1    RHC   2  9   25.5 187 1351 91.75962 129.5763 2184       0
2 No RHC   2  9   25.0 191 1243 95.57871 117.7174 3551       0
```

These seem quite comparable, so far, and again, they make sense (all are
positive, and there are no missing values.)

# The 50 Covariates We’ll Study

Our propensity model will eventually include 50 covariates, described
below.

## Group 1: Socio-demographics (6 covariates)

| Variable   | Definition                    |
| ---------- | ----------------------------- |
| `age`      | Age in years                  |
| `sex`      | Sex                           |
| `edu`      | Years of Education            |
| `income`   | Income Category (4 levels)    |
| `ninsclas` | Insurance Category (6 levels) |
| `race`     | Self-Reported Race (3 levels) |

Here’s a Table 1 for these covariates.

``` r
vars01 <- c("age", "sex", "edu", "income", "ninsclas", "race")

table1_01 <- 
    CreateTableOne(vars = vars01, strata = "swang1", 
                   data = rhc_cleaning, test = FALSE)

print(table1_01, smd = TRUE)
```

``` 
                        Stratified by swang1
                         RHC           No RHC        SMD   
  n                       2184          3551               
  age (mean (SD))        60.75 (15.63) 61.76 (17.29)  0.061
  sex = Female (%)         906 (41.5)   1637 (46.1)   0.093
  edu (mean (SD))        11.86 (3.16)  11.57 (3.13)   0.091
  income (%)                                          0.142
     Under $11k           1145 (52.4)   2081 (58.6)        
     $11-$25k              452 (20.7)    713 (20.1)        
     $25-$50k              393 (18.0)    500 (14.1)        
     > $50k                194 ( 8.9)    257 ( 7.2)        
  ninsclas (%)                                        0.194
     Private               731 (33.5)    967 (27.2)        
     Private & Medicare    490 (22.4)    746 (21.0)        
     Medicare              511 (23.4)    947 (26.7)        
     Medicare & Medicaid   123 ( 5.6)    251 ( 7.1)        
     Medicaid              193 ( 8.8)    454 (12.8)        
     No insurance          136 ( 6.2)    186 ( 5.2)        
  race (%)                                            0.036
     white                1707 (78.2)   2753 (77.5)        
     black                 335 (15.3)    585 (16.5)        
     other                 142 ( 6.5)    213 ( 6.0)        
```

  - Two of these covariates show standardized mean differences larger
    than 0.10.

## Group 2: Presentation at Admission (7 covariates)

| Variable  | Definition                          |
| --------- | ----------------------------------- |
| `cat1`    | Primary disease category (9 levels) |
| `dnr1`    | Do Not Resuscitate status, day 1    |
| `wtkilo1` | Weight in kg, day 1                 |
| `hrt1`    | Heart rate, day 1                   |
| `meanbp1` | Mean Blood Pressure, day 1          |
| `resp1`   | Respiratory rate, day 1             |
| `temp1`   | Temperature, C, day 1               |

``` r
vars02 <- c("cat1", "dnr1", "wtkilo1", "hrt1", "meanbp1", 
          "resp1", "temp1")

table1_02 <- 
    CreateTableOne(vars = vars02, strata = "swang1", 
                   data = rhc_cleaning, test = FALSE)

print(table1_02, smd = TRUE)
```

``` 
                      Stratified by swang1
                       RHC            No RHC         SMD   
  n                      2184           3551               
  cat1 (%)                                            0.583
     ARF                  909 (41.6)    1581 (44.5)        
     CHF                  209 ( 9.6)     247 ( 7.0)        
     Cirrhosis             49 ( 2.2)     175 ( 4.9)        
     Colon Cancer           1 ( 0.0)       6 ( 0.2)        
     Coma                  95 ( 4.3)     341 ( 9.6)        
     COPD                  58 ( 2.7)     399 (11.2)        
     Lung Cancer            5 ( 0.2)      34 ( 1.0)        
     MOSF w/Malignancy    158 ( 7.2)     241 ( 6.8)        
     MOSF w/Sepsis        700 (32.1)     527 (14.8)        
  dnr1 = Yes (%)          155 ( 7.1)     499 (14.1)   0.228
  wtkilo1 (mean (SD))   72.36 (27.73)  65.04 (29.50)  0.256
  hrt1 (mean (SD))     118.93 (41.47) 112.87 (40.94)  0.147
  meanbp1 (mean (SD))   68.20 (34.24)  84.87 (38.87)  0.455
  resp1 (mean (SD))     26.65 (14.17)  28.98 (13.95)  0.165
  temp1 (mean (SD))     37.59 (1.83)   37.63 (1.74)   0.021
```

  - Six of these covariates show standardized mean differences larger
    than 0.10.

## Group 3: Admission Diagnosis Categories (10 covariates)

| Variable | Definition                 |
| -------- | -------------------------- |
| `card`   | Cardiovascular diagnosis   |
| `gastr`  | Gastrointestinal diagnosis |
| `hema`   | Hematologic diagnosis      |
| `meta`   | Metabolic diagnosis        |
| `neuro`  | Neurological diagnosis     |
| `ortho`  | Orthopedic diagnosis       |
| `renal`  | Renal diagnosis            |
| `resp`   | Respiratory diagnosis      |
| `seps`   | Sepsis diagnosis           |
| `trauma` | Trauma diagnosis           |

``` r
vars03 <- c("card", "gastr", "hema", "meta", "neuro", "ortho",
          "renal", "resp", "seps", "trauma")

table1_03 <- 
    CreateTableOne(vars = vars03, strata = "swang1", 
                   data = rhc_cleaning, test = FALSE)

print(table1_03, smd = TRUE)
```

``` 
                  Stratified by swang1
                   RHC          No RHC       SMD   
  n                2184         3551               
  card = Yes (%)    924 (42.3)  1007 (28.4)   0.295
  gastr = Yes (%)   420 (19.2)   522 (14.7)   0.121
  hema = Yes (%)    115 ( 5.3)   239 ( 6.7)   0.062
  meta = Yes (%)     93 ( 4.3)   172 ( 4.8)   0.028
  neuro = Yes (%)   118 ( 5.4)   575 (16.2)   0.353
  ortho = Yes (%)     4 ( 0.2)     3 ( 0.1)   0.027
  renal = Yes (%)   148 ( 6.8)   147 ( 4.1)   0.116
  resp = Yes (%)    632 (28.9)  1481 (41.7)   0.270
  seps = Yes (%)    516 (23.6)   515 (14.5)   0.234
  trauma = Yes (%)   34 ( 1.6)    18 ( 0.5)   0.104
```

  - Seven of these covariates show standardized mean differences larger
    than
0.10.

## Group 4: Comorbid Illness and Transfer Status (13 covariates)

| Variable   | Definition                                                                                                                                                          |
| ---------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `amihx`    | Definite Myocardial Infarction                                                                                                                                      |
| `ca`       | Cancer (3 levels)                                                                                                                                                   |
| `cardiohx` | Acute MI, Peripheral Vascular Disease, Severe Cardiovascular Symptoms (NYHA-Class III), Very Severe Cardiovascular Symptoms (NYHA- IV)                              |
| `chfhx`    | Congestive Heart Failure                                                                                                                                            |
| `chrpulhx` | Chronic Pulmonary Disease, Severe or Very Severe Pulmonary Disease                                                                                                  |
| `dementhx` | Dementia, Stroke or Cerebral Infarct, Parkinson’s Disease                                                                                                           |
| `gibledhx` | Upper GI Bleeding                                                                                                                                                   |
| `immunhx`  | Immunosupperssion, Organ Transplant, HIV Positivity, Diabetes Mellitus Without End Organ Damage, Diabetes Mellitus With End Organ Damage, Connective Tissue Disease |
| `liverhx`  | Cirrhosis, Hepatic Failure                                                                                                                                          |
| `malighx`  | Solid Tumor, Metastatic Disease, Chronic Leukemia/Myeloma, Acute Leukemia, Lymphoma                                                                                 |
| `psychhx`  | Psychiatric History, Active Psychosis or Severe Depression                                                                                                          |
| `renalhx`  | Chronic Renal Disease, Chronic Hemodialysis or Peritoneal Dialysis                                                                                                  |
| `transhx`  | Transfer (\> 24 Hours) from Another Hospital                                                                                                                        |

``` r
vars04 <- c("amihx", "ca", "cardiohx", "chfhx", "chrpulhx", "dementhx",
          "gibledhx", "immunhx", "liverhx", "malighx", "psychhx", "renalhx", "transhx")

table1_04 <- 
    CreateTableOne(vars = vars04, strata = "swang1", 
                   data = rhc_cleaning, test = FALSE)

print(table1_04, smd = TRUE)
```

``` 
                      Stratified by swang1
                       RHC          No RHC       SMD   
  n                    2184         3551               
  amihx (mean (SD))    0.04 (0.20)  0.03 (0.17)   0.074
  ca (%)                                          0.107
     No                1727 (79.1)  2652 (74.7)        
     Yes                334 (15.3)   638 (18.0)        
     Metastatic         123 ( 5.6)   261 ( 7.4)        
  cardiohx (mean (SD)) 0.20 (0.40)  0.16 (0.37)   0.116
  chfhx (mean (SD))    0.19 (0.40)  0.17 (0.37)   0.069
  chrpulhx (mean (SD)) 0.14 (0.35)  0.22 (0.41)   0.192
  dementhx (mean (SD)) 0.07 (0.25)  0.12 (0.32)   0.163
  gibledhx (mean (SD)) 0.02 (0.16)  0.04 (0.19)   0.070
  immunhx (mean (SD))  0.29 (0.45)  0.26 (0.44)   0.080
  liverhx (mean (SD))  0.06 (0.24)  0.07 (0.26)   0.049
  malighx (mean (SD))  0.20 (0.40)  0.25 (0.43)   0.101
  psychhx (mean (SD))  0.05 (0.21)  0.08 (0.27)   0.143
  renalhx (mean (SD))  0.05 (0.21)  0.04 (0.20)   0.032
  transhx (mean (SD))  0.15 (0.36)  0.09 (0.29)   0.170
```

  - Seven of these covariates show standardized mean differences larger
    than
0.10.

## Group 5: Day 1 Summary Measures of Presentation / Severity of Illness (4 covariates)

| Variable   | Definition                                           |
| ---------- | ---------------------------------------------------- |
| `aps1`     | APACHE III score ignoring Coma, day 1                |
| `das2d3pc` | DASI (Duke Activity Status Index prior to admission) |
| `scoma1`   | Support Coma score based on Glasgow, day 1           |
| `surv2md1` | SUPPORT model estimate of Prob(surviving 2 months)   |

``` r
vars05 <- c("aps1", "das2d3pc", "scoma1", "surv2md1")

table1_05 <- 
    CreateTableOne(vars = vars05, strata = "swang1", 
                   data = rhc_cleaning, test = FALSE)

print(table1_05, smd = TRUE)
```

``` 
                      Stratified by swang1
                       RHC           No RHC        SMD   
  n                     2184          3551               
  aps1 (mean (SD))     60.74 (20.27) 50.93 (18.81)  0.501
  das2d3pc (mean (SD)) 20.70 (5.03)  20.37 (5.48)   0.063
  scoma1 (mean (SD))   18.97 (28.26) 22.25 (31.37)  0.110
  surv2md1 (mean (SD))  0.57 (0.20)   0.61 (0.19)   0.198
```

  - Three of these covariates show standardized mean differences larger
    than 0.10.

## Group 6: Day 1 Lab Results (10 covariates)

| Variable | Definition                                       |
| -------- | ------------------------------------------------ |
| `alb1`   | Albumin                                          |
| `bili1`  | Bilirubin                                        |
| `crea1`  | Serum Creatinine                                 |
| `hema1`  | Hematocrit                                       |
| `paco21` | PaCo2                                            |
| `pafi1`  | PaO2/(.01 FIO2)                                  |
| `ph1`    | Serum PH (arterial)                              |
| `pot1`   | Serum Potassium                                  |
| `sod1`   | Serum Sodium                                     |
| `wblc1`  | White blood cell count (4 subjects with value 0) |

``` r
vars06 <- c("alb1", "bili1", "crea1", "hema1", "paco21",
            "pafi1", "pot1", "sod1", "wblc1")

table1_06 <- 
    CreateTableOne(vars = vars06, strata = "swang1", 
                   data = rhc_cleaning, test = FALSE)

print(table1_06, smd = TRUE)
```

``` 
                    Stratified by swang1
                     RHC             No RHC          SMD   
  n                    2184            3551                
  alb1 (mean (SD))     2.98 (0.93)     3.16 (0.67)    0.230
  bili1 (mean (SD))    2.71 (5.33)     2.00 (4.43)    0.145
  crea1 (mean (SD))    2.47 (2.05)     1.92 (2.03)    0.270
  hema1 (mean (SD))   30.51 (7.42)    32.70 (8.79)    0.269
  paco21 (mean (SD))  36.79 (10.97)   39.95 (14.24)   0.249
  pafi1 (mean (SD))  192.43 (105.54) 240.63 (116.66)  0.433
  pot1 (mean (SD))     4.05 (1.01)     4.08 (1.04)    0.027
  sod1 (mean (SD))   136.33 (7.60)   137.04 (7.68)    0.092
  wblc1 (mean (SD))   16.27 (12.55)   15.26 (11.41)   0.084
```

  - Six of these covariates show standardized mean differences larger
    than 0.10.

So, in all, 31 of the 50 covariates show standardized mean differences
that exceed 0.10 before any propensity score adjustment.

# A Little Refactoring

For our outcome, and our treatment, it will be useful to have 1/0
versions of the variables, and it will also be helpful to have the
factor versions releveled to put the outcome of interest (death) first
and the treatment of interest (RHC) first.

``` r
rhc <- rhc_cleaning %>%
    mutate(treat_rhc = as.numeric(swang1 == "RHC"),
           swang1 = fct_relevel(swang1, "RHC"),
           death = fct_relevel(death, "Yes"),
           died = as.numeric(death == "Yes"))
```

## Saving the Data File

``` r
saveRDS(rhc, here("data", "rhc.Rds"))
```

# Unadjusted Outcome Assessments

Before we estimate a propensity score, we’ll perform unadjusted
assessments to describe the impact of RHC (or not) on our three
outcomes, without adjustment for any covariates at all.

## Outcome A: In-Study Mortality (binary)

``` r
rhc %>% tabyl(swang1, death) %>% 
    adorn_totals() %>%
    adorn_percentages() %>%
    adorn_pct_formatting() %>%
    adorn_ns(position = "front") %>%
    adorn_title
```

``` 
               death             
 swang1          Yes           No
    RHC 1486 (68.0%)  698 (32.0%)
 No RHC 2236 (63.0%) 1315 (37.0%)
  Total 3722 (64.9%) 2013 (35.1%)
```

The odds ratio of death associated with RHC as opposed to No RHC should
be larger than 1, specifically, it should be

\[
\frac{1486 \times 1315}{2236 \times 698} = 1.25
\]

Let’s see if that’s what we get.

### Fitting the Model with the 1/0 treatment and outcome

``` r
death_unadj <- glm(died ~ treat_rhc, data = rhc, family = binomial())

death_unadj
```

``` 

Call:  glm(formula = died ~ treat_rhc, family = binomial(), data = rhc)

Coefficients:
(Intercept)    treat_rhc  
     0.5309       0.2248  

Degrees of Freedom: 5734 Total (i.e. Null);  5733 Residual
Null Deviance:      7433 
Residual Deviance: 7418     AIC: 7422
```

``` r
tidy(death_unadj, conf.int = TRUE, exponentiate = TRUE)
```

    # A tibble: 2 x 7
      term        estimate std.error statistic  p.value conf.low conf.high
      <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 (Intercept)     1.70    0.0348     15.3  1.11e-52     1.59      1.82
    2 treat_rhc       1.25    0.0576      3.90 9.43e- 5     1.12      1.40

### Fitting the Model with the treatment and outcome as factors requires care

Alternatively, we could just work with the factors, but then, it’s
important to be sure what is actually being modeled. Do this by making
the outcome and treatment logical results, as
follows.

``` r
modelA_unadj1 <- glm((death == "Yes") ~ (swang1 == "RHC"), data = rhc, family = binomial())

tidy(modelA_unadj1, conf.int = TRUE, exponentiate = TRUE)
```

    # A tibble: 2 x 7
      term             estimate std.error statistic  p.value conf.low conf.high
      <chr>               <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 (Intercept)          1.70    0.0348     15.3  1.11e-52     1.59      1.82
    2 "swang1 == \"RH~     1.25    0.0576      3.90 9.43e- 5     1.12      1.40

Failing to do this can cause trouble:

``` r
modelA_unadj_bad <- glm(death ~ swang1, data = rhc, family = binomial())

tidy(modelA_unadj_bad, conf.int = TRUE, exponentiate = TRUE)
```

    # A tibble: 2 x 7
      term         estimate std.error statistic  p.value conf.low conf.high
      <chr>           <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 (Intercept)     0.470    0.0459    -16.5  6.32e-61    0.429     0.514
    2 swang1No RHC    1.25     0.0576      3.90 9.43e- 5    1.12      1.40 

Note that this last version is actually predicting “Death = No” on the
basis of “swang1 = No RHC”, which can be extremely confusing.

And if you did
this:

``` r
modelA_unadj_bad2 <- glm(death ~ swang1 == "RHC", data = rhc, family = binomial())

tidy(modelA_unadj_bad2, conf.int = TRUE, exponentiate = TRUE)
```

    # A tibble: 2 x 7
      term             estimate std.error statistic  p.value conf.low conf.high
      <chr>               <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 (Intercept)         0.588    0.0348    -15.3  1.11e-52    0.549     0.629
    2 "swang1 == \"RH~    0.799    0.0576     -3.90 9.43e- 5    0.713     0.894

Now, you’ve inverted the odds ratio\! Not good. So, either use 0 and 1
(with 1 being the result you want to study), or use the factors but
specify the direction for both treatment and outcome as a logical
statement.

## Outcome B: Length of Stay (quantitative)

``` r
hospdays_unadj <- glm(hospdays ~ treat_rhc, data = rhc)

hospdays_unadj
```

``` 

Call:  glm(formula = hospdays ~ treat_rhc, data = rhc)

Coefficients:
(Intercept)    treat_rhc  
     19.529        5.162  

Degrees of Freedom: 5734 Total (i.e. Null);  5733 Residual
Null Deviance:      3698000 
Residual Deviance: 3662000  AIC: 53320
```

``` r
tidy(hospdays_unadj, conf.int = TRUE)
```

    # A tibble: 2 x 7
      term        estimate std.error statistic  p.value conf.low conf.high
      <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 (Intercept)    19.5      0.424     46.0  0.          18.7      20.4 
    2 treat_rhc       5.16     0.687      7.51 6.76e-14     3.82      6.51

## Outcome C: Time to death (time-to-event)

Here’s the data on `survdays` and `death` for our first six patients:

``` r
rhc %>% select(survdays, death) %>% head()
```

``` 
# A tibble: 6 x 2
  survdays death
     <dbl> <fct>
1      240 No   
2       45 Yes  
3      317 No   
4       37 Yes  
5        2 Yes  
6      201 No   
```

Here, we have a (right-censored) time to event outcome, called
`survdays`, and an indicator of censoring (`death` which is “Yes” if the
patient’s time is real and not censored). So the first subject should
have a time to death of 240 or more days, because they were still alive
when the study ended, while the second should have a time that is
exactly 45 days, because that person died during the study. The survival
object we need, then,
is:

``` r
Surv(rhc$survdays, rhc$death == "Yes") %>% head()
```

    [1] 240+  45  317+  37    2  201+

``` r
survdays_unadj <- coxph(Surv(survdays, death == "Yes") ~ treat_rhc, data = rhc)

survdays_unadj
```

    Call:
    coxph(formula = Surv(survdays, death == "Yes") ~ treat_rhc, data = rhc)
    
                 coef exp(coef) se(coef)     z      p
    treat_rhc 0.07841   1.08156  0.03347 2.342 0.0192
    
    Likelihood ratio test=5.46  on 1 df, p=0.0195
    n= 5735, number of events= 3722 

``` r
tidy(survdays_unadj, conf.int = TRUE, exponentiate = TRUE)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.08    0.0335      2.34  0.0192     1.01      1.15

# Estimate the Propensity Score with Logistic Regression

``` r
propensity_model <- 
    glm(swang1 == "RHC"  ~ 
            age + sex + edu + income + ninsclas + race +
            cat1 + dnr1 + wtkilo1 + hrt1 + meanbp1 + 
            resp1 + temp1 +
            card + gastr + hema + meta + neuro + ortho + 
            renal + resp + seps + trauma +
            amihx + ca + cardiohx + chfhx + chrpulhx +
            dementhx + gibledhx + immunhx + liverhx +
            malighx + psychhx + renalhx + transhx +
            aps1 + das2d3pc + scoma1 + surv2md1 +
            alb1 + bili1 + crea1 + hema1 + paco21 + pafi1 +
            ph1 + pot1 + sod1 + wblc1,
        family = binomial(link = "logit"), data = rhc)
```

## Store the propensity scores and linear propensity scores

``` r
rhc <- rhc %>%
    mutate(ps = fitted(propensity_model),
           linps = propensity_model$linear.predictors)

rhc %>% select(ptid, ps, linps) %>% head()
```

    # A tibble: 6 x 3
      ptid      ps  linps
      <chr>  <dbl>  <dbl>
    1 00005 0.351  -0.615
    2 00007 0.669   0.704
    3 00009 0.634   0.547
    4 00010 0.369  -0.537
    5 00011 0.446  -0.218
    6 00012 0.0553 -2.84 

## Plot the Propensity Scores to Verify that they Match Your Expectations

``` r
ggplot(rhc, aes(x = ps, fill = swang1)) +
    geom_density(alpha = 0.5) +
    scale_fill_viridis_d(option = "plasma") +
    theme_bw()
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-23-1.png)<!-- -->

``` r
ggplot(rhc, aes(x = swang1, y = ps)) +
    geom_violin(aes(fill = swang1)) + 
    geom_boxplot(width = 0.2) +
    scale_fill_viridis_d(option = "plasma") + 
    guides(fill = FALSE) + 
    coord_flip() +
    theme_bw()
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-24-1.png)<!-- -->

OK. We’re trying to use `ps` to estimate the probability of having a
RHC, and it looks the people who actually had RHC have higher PS, on
average, so that’s promising.

# Checking Rubin’s Rules Prior to Propensity Adjustment

Rubin Rule 1 result should ideally be near 0, and certainly between -50
and +50.

``` r
rubin1.unadj <- with(rhc, 
                  abs(100*(mean(linps[swang1=="RHC"]) - 
                               mean(linps[swang1=="No RHC"]))/
                          sd(linps)))
rubin1.unadj
```

    [1] 101.583

Rubin Rule 2 result should ideally be near 1, and certainly between 1/2
and 2.

``` r
rubin2.unadj <- with(rhc, 
                  var(linps[swang1 == "RHC"]) / 
                      var(linps[swang1 == "No RHC"]))
rubin2.unadj
```

    [1] 0.7359463

So, we’ve got some work to do. Let’s try matching. In several different
ways.

# Match 1: 1:1 Greedy Matching on the linear PS, without Replacement

``` r
Y <- rhc$hospdays
X <- rhc$linps
Tr <- as.logical(rhc$swang1 == "RHC")
match1 <- Match(Y = Y, Tr = Tr, X = X, M = 1, 
                estimand = "ATT", replace = FALSE, 
                ties = FALSE)
summary(match1)
```

``` 

Estimate...  3.6836 
SE.........  0.81189 
T-stat.....  4.5371 
p.val......  5.7035e-06 

Original number of observations..............  5735 
Original number of treated obs...............  2184 
Matched number of observations...............  2184 
Matched number of observations  (unweighted).  2184 
```

## Love Plot for Match 1

``` r
b1 <- bal.tab(match1, 
              swang1 == "RHC"  ~ 
                  age + sex + edu + income + ninsclas + race +
                  cat1 + dnr1 + wtkilo1 + hrt1 + meanbp1 + 
                  resp1 + temp1 +
                  card + gastr + hema + meta + neuro + ortho + 
                  renal + resp + seps + trauma +
                  amihx + ca + cardiohx + chfhx + chrpulhx +
                  dementhx + gibledhx + immunhx + liverhx +
                  malighx + psychhx + renalhx + transhx +
                  aps1 + das2d3pc + scoma1 + surv2md1 +
                  alb1 + bili1 + crea1 + hema1 + paco21 + pafi1 +
                  ph1 + pot1 + sod1 + wblc1 + ps + linps,
              data=rhc, un = TRUE)

love.plot(b1, threshold = .1, size = 1.5,
               var.order = "unadjusted",
               title = "Standardized Differences and Match 1") +
    theme_bw()
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-28-1.png)<!-- -->

## Rubin’s Rules 1 and 2 for Match 1

Create a new data frame, containing only the matched sample.

``` r
matches_1 <- factor(rep(match1$index.treated, 2))
rhc.matches_1 <- cbind(matches_1, 
          rhc[c(match1$index.control, match1$index.treated),])
```

Rubin Rule 1 result after matching should ideally be near 0, and
certainly between -50 and +50.

``` r
rubin1.m1 <- with(rhc.matches_1, 
                  abs(100*(mean(linps[swang1=="RHC"]) - 
                               mean(linps[swang1=="No RHC"]))/
                          sd(linps)))
rubin1.m1
```

    [1] 61.88411

Rubin Rule 2 result after matching should ideally be near 1, and
certainly between 1/2 and 2.

``` r
rubin2.m1 <- with(rhc.matches_1, 
                  var(linps[swang1 == "RHC"]) / 
                      var(linps[swang1 == "No RHC"]))
rubin2.m1
```

    [1] 1.68714

# Match 2: 1:2 Greedy Matching on the linear PS, without Replacement

``` r
Y <- rhc$hospdays
X <- rhc$linps
Tr <- as.logical(rhc$swang1 == "RHC")
match2 <- Match(Y = Y, Tr = Tr, X = X, M = 2, 
                estimand = "ATT", replace = FALSE, 
                ties = FALSE)
summary(match2)
```

``` 

Estimate...  4.9814 
SE.........  0.86512 
T-stat.....  5.758 
p.val......  8.5104e-09 

Original number of observations..............  5735 
Original number of treated obs...............  2184 
Matched number of observations...............  1775 
Matched number of observations  (unweighted).  3550 
```

## Love Plot for Match 2

``` r
b2 <- bal.tab(match2, 
              swang1 == "RHC"  ~ 
                  age + sex + edu + income + ninsclas + race +
                  cat1 + dnr1 + wtkilo1 + hrt1 + meanbp1 + 
                  resp1 + temp1 +
                  card + gastr + hema + meta + neuro + ortho + 
                  renal + resp + seps + trauma +
                  amihx + ca + cardiohx + chfhx + chrpulhx +
                  dementhx + gibledhx + immunhx + liverhx +
                  malighx + psychhx + renalhx + transhx +
                  aps1 + das2d3pc + scoma1 + surv2md1 +
                  alb1 + bili1 + crea1 + hema1 + paco21 + pafi1 +
                  ph1 + pot1 + sod1 + wblc1 + ps + linps,
              data=rhc, un = TRUE)

love.plot(b2, threshold = .1, size = 1.5,
               var.order = "unadjusted",
               title = "Standardized Differences and Match 2") +
    theme_bw()
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-33-1.png)<!-- -->

## Rubin’s Rules 1 and 2 for Match 2

Create a new data frame, containing only the matched sample.

``` r
matches_2 <- factor(rep(match2$index.treated, 2))
rhc.matches_2 <- cbind(matches_2, 
          rhc[c(match2$index.control, match2$index.treated),])
```

Rubin Rule 1 result after matching should ideally be near 0, and
certainly between -50 and +50.

``` r
rubin1.m2 <- with(rhc.matches_2, 
                  abs(100*(mean(linps[swang1=="RHC"]) - 
                               mean(linps[swang1=="No RHC"]))/
                          sd(linps)))
rubin1.m2
```

    [1] 101.2148

Rubin Rule 2 result after matching should ideally be near 1, and
certainly between 1/2 and 2.

``` r
rubin2.m2 <- with(rhc.matches_2, 
                  var(linps[swang1 == "RHC"]) / 
                      var(linps[swang1 == "No RHC"]))
rubin2.m2
```

    [1] 0.7569187

# Match 3: Genetic Search Matching to do 1:1 Matching without replacement

The `GenMatch` function finds optimal balance using multivariate
matching where a genetic search algorithm determines the weight that
each covariate is given.

Please note that I am using way too small values of `pop.size`
(especially) and probably `max.generations`, too, so that things run
quickly. I am also only matching on the propensity score and linear
propensity score, rather than on the individual covariates. For a course
project, I recommend you try matching on the individual covariates if
you can, but this reduction in the paramater values is fine.

For actual publications, follow the recommendations of the `GenMatch`
algorithm, as described in the `Matching` and `genoud` package help
files. The default values (which may be too small themselves) are 100
for both `pop.size` and `max.generations`.

``` r
Y <- rhc$hospdays
X <- cbind(rhc$linps, rhc$ps)
Tr <- as.logical(rhc$swang1 == "RHC")
genout3 <- GenMatch(Tr = Tr, X = X,
                    estimand = "ATT", M = 1,
                    pop.size = 10, max.generations = 10,
                    wait.generations = 4, verbose = FALSE)
```

``` 


Thu Mar 14 11:59:18 2019
Domains:
 0.000000e+00   <=  X1   <=    1.000000e+03 
 0.000000e+00   <=  X2   <=    1.000000e+03 

Data Type: Floating Point
Operators (code number, name, population) 
    (1) Cloning...........................  0
    (2) Uniform Mutation..................  1
    (3) Boundary Mutation.................  1
    (4) Non-Uniform Mutation..............  1
    (5) Polytope Crossover................  1
    (6) Simple Crossover..................  2
    (7) Whole Non-Uniform Mutation........  1
    (8) Heuristic Crossover...............  2
    (9) Local-Minimum Crossover...........  0

SOFT Maximum Number of Generations: 10
Maximum Nonchanging Generations: 4
Population size       : 10
Convergence Tolerance: 1.000000e-03

Not Using the BFGS Derivative Based Optimizer on the Best Individual Each Generation.
Not Checking Gradients before Stopping.
Using Out of Bounds Individuals.

Maximization Problem.
GENERATION: 0 (initializing the population)
Lexical Fit..... 1.312609e-01  2.262862e-01  1.000000e+00  1.000000e+00  
#unique......... 10, #Total UniqueCount: 10
var 1:
best............ 7.442759e+01
mean............ 4.123626e+02
variance........ 6.269946e+04
var 2:
best............ 2.135063e+02
mean............ 4.509171e+02
variance........ 7.659116e+04

GENERATION: 1
Lexical Fit..... 1.312609e-01  2.262862e-01  1.000000e+00  1.000000e+00  
#unique......... 6, #Total UniqueCount: 16
var 1:
best............ 7.442759e+01
mean............ 2.940527e+02
variance........ 9.349197e+04
var 2:
best............ 2.135063e+02
mean............ 3.048586e+02
variance........ 3.801714e+04

GENERATION: 2
Lexical Fit..... 1.313747e-01  2.270265e-01  1.000000e+00  1.000000e+00  
#unique......... 5, #Total UniqueCount: 21
var 1:
best............ 7.442759e+01
mean............ 9.985209e+01
variance........ 3.714259e+03
var 2:
best............ 2.252333e+02
mean............ 2.889448e+02
variance........ 4.655945e+04

GENERATION: 3
Lexical Fit..... 1.313747e-01  2.270265e-01  1.000000e+00  1.000000e+00  
#unique......... 5, #Total UniqueCount: 26
var 1:
best............ 7.442759e+01
mean............ 1.164295e+02
variance........ 1.470110e+04
var 2:
best............ 2.252333e+02
mean............ 2.254410e+02
variance........ 3.443109e+02

GENERATION: 4
Lexical Fit..... 1.314101e-01  2.271296e-01  1.000000e+00  1.000000e+00  
#unique......... 5, #Total UniqueCount: 31
var 1:
best............ 6.783555e+01
mean............ 8.176836e+01
variance........ 5.491254e+02
var 2:
best............ 2.281709e+02
mean............ 2.256806e+02
variance........ 4.623490e+00

GENERATION: 5
Lexical Fit..... 1.314101e-01  2.271296e-01  1.000000e+00  1.000000e+00  
#unique......... 7, #Total UniqueCount: 38
var 1:
best............ 6.783555e+01
mean............ 6.625746e+01
variance........ 1.510078e+02
var 2:
best............ 2.281709e+02
mean............ 2.153930e+02
variance........ 1.288237e+03

'wait.generations' limit reached.
No significant improvement in 4 generations.

Solution Lexical Fitness Value:
1.314101e-01  2.271296e-01  1.000000e+00  1.000000e+00  

Parameters at the Solution:

 X[ 1] :    6.783555e+01
 X[ 2] :    2.281709e+02

Solution Found Generation 1
Number of Generations Run 5

Thu Mar 14 11:59:33 2019
Total run time : 0 hours 0 minutes and 15 seconds
```

``` r
match3 <- Match(Y = Y, Tr = Tr, X = X, estimand = "ATT", 
                 Weight.matrix = genout3)
summary(match3)
```

``` 

Estimate...  1.4573 
AI SE......  1.3616 
T-stat.....  1.0703 
p.val......  0.2845 

Original number of observations..............  5735 
Original number of treated obs...............  2184 
Matched number of observations...............  2184 
Matched number of observations  (unweighted).  2364 
```

## Love Plot for Match 3

``` r
b3 <- bal.tab(match3, 
              swang1 == "RHC"  ~ 
                  age + sex + edu + income + ninsclas + race +
                  cat1 + dnr1 + wtkilo1 + hrt1 + meanbp1 + 
                  resp1 + temp1 +
                  card + gastr + hema + meta + neuro + ortho + 
                  renal + resp + seps + trauma +
                  amihx + ca + cardiohx + chfhx + chrpulhx +
                  dementhx + gibledhx + immunhx + liverhx +
                  malighx + psychhx + renalhx + transhx +
                  aps1 + das2d3pc + scoma1 + surv2md1 +
                  alb1 + bili1 + crea1 + hema1 + paco21 + pafi1 +
                  ph1 + pot1 + sod1 + wblc1 + ps + linps,
              data=rhc, un = TRUE)

love.plot(b3, threshold = .1, size = 1.5,
               var.order = "unadjusted",
               title = "Standardized Differences and Match 3") +
    theme_bw()
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-38-1.png)<!-- -->

## Rubin’s Rules 1 and 2 for Match 3

Create a new data frame, containing only the matched sample.

``` r
matches_3 <- factor(rep(match3$index.treated, 2))
rhc.matches_3 <- cbind(matches_3, 
          rhc[c(match3$index.control, match3$index.treated),])
```

Rubin Rule 1 result after matching should ideally be near 0, and
certainly between -50 and +50.

``` r
rubin1.m3 <- with(rhc.matches_3, 
                  abs(100*(mean(linps[swang1=="RHC"]) - 
                               mean(linps[swang1=="No RHC"]))/
                          sd(linps)))
rubin1.m3
```

    [1] 0.04710403

Rubin Rule 2 result after matching should ideally be near 1, and
certainly between 1/2 and 2.

``` r
rubin2.m3 <- with(rhc.matches_3, 
                  var(linps[swang1 == "RHC"]) / 
                      var(linps[swang1 == "No RHC"]))
rubin2.m3
```

    [1] 1.00246

# Match 4: 1:1 Greedy Matching on the linear PS, WITH Replacement

``` r
Y <- rhc$hospdays
X <- rhc$linps
Tr <- as.logical(rhc$swang1 == "RHC")
match4 <- Match(Y = Y, Tr = Tr, X = X, M = 1, 
                estimand = "ATT", replace = FALSE, 
                ties = FALSE)
summary(match4)
```

``` 

Estimate...  3.647 
SE.........  0.80744 
T-stat.....  4.5167 
p.val......  6.2807e-06 

Original number of observations..............  5735 
Original number of treated obs...............  2184 
Matched number of observations...............  2184 
Matched number of observations  (unweighted).  2184 
```

## Love Plot for Match 4

``` r
b4 <- bal.tab(match4, 
              swang1 == "RHC"  ~ 
                  age + sex + edu + income + ninsclas + race +
                  cat1 + dnr1 + wtkilo1 + hrt1 + meanbp1 + 
                  resp1 + temp1 +
                  card + gastr + hema + meta + neuro + ortho + 
                  renal + resp + seps + trauma +
                  amihx + ca + cardiohx + chfhx + chrpulhx +
                  dementhx + gibledhx + immunhx + liverhx +
                  malighx + psychhx + renalhx + transhx +
                  aps1 + das2d3pc + scoma1 + surv2md1 +
                  alb1 + bili1 + crea1 + hema1 + paco21 + pafi1 +
                  ph1 + pot1 + sod1 + wblc1 + ps + linps,
              data=rhc, un = TRUE)

love.plot(b4, threshold = .1, size = 1.5,
               var.order = "unadjusted",
               title = "Standardized Differences and Match 4") +
    theme_bw()
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-43-1.png)<!-- -->

## Rubin’s Rules 1 and 2 for Match 4

Create a new data frame, containing only the matched sample.

``` r
matches_4 <- factor(rep(match4$index.treated, 2))
rhc.matches_4 <- cbind(matches_4, 
          rhc[c(match4$index.control, match4$index.treated),])
```

Rubin Rule 1 result after matching should ideally be near 0, and
certainly between -50 and +50.

``` r
rubin1.m4 <- with(rhc.matches_4, 
                  abs(100*(mean(linps[swang1=="RHC"]) - 
                               mean(linps[swang1=="No RHC"]))/
                          sd(linps)))
rubin1.m4
```

    [1] 61.88437

Rubin Rule 2 result after matching should ideally be near 1, and
certainly between 1/2 and 2.

``` r
rubin2.m4 <- with(rhc.matches_4, 
                  var(linps[swang1 == "RHC"]) / 
                      var(linps[swang1 == "No RHC"]))
rubin2.m4
```

    [1] 1.687111

# Match 5: 1:1 Caliper Matching on the linear PS, WITH Replacement

``` r
Y <- rhc$hospdays
X <- rhc$linps
Tr <- as.logical(rhc$swang1 == "RHC")
match5 <- Match(Y = Y, Tr = Tr, X = X, M = 1, 
                caliper = 0.2,
                estimand = "ATT", replace = FALSE, 
                ties = FALSE)
summary(match5)
```

``` 

Estimate...  2.2054 
SE.........  0.90603 
T-stat.....  2.4341 
p.val......  0.014929 

Original number of observations..............  5735 
Original number of treated obs...............  2184 
Matched number of observations...............  1563 
Matched number of observations  (unweighted).  1563 

Caliper (SDs)........................................   0.2 
Number of obs dropped by 'exact' or 'caliper'  621 
```

## Love Plot for Match 5

``` r
b5 <- bal.tab(match5, 
              swang1 == "RHC"  ~ 
                  age + sex + edu + income + ninsclas + race +
                  cat1 + dnr1 + wtkilo1 + hrt1 + meanbp1 + 
                  resp1 + temp1 +
                  card + gastr + hema + meta + neuro + ortho + 
                  renal + resp + seps + trauma +
                  amihx + ca + cardiohx + chfhx + chrpulhx +
                  dementhx + gibledhx + immunhx + liverhx +
                  malighx + psychhx + renalhx + transhx +
                  aps1 + das2d3pc + scoma1 + surv2md1 +
                  alb1 + bili1 + crea1 + hema1 + paco21 + pafi1 +
                  ph1 + pot1 + sod1 + wblc1 + ps + linps,
              data=rhc, un = TRUE)

love.plot(b5, threshold = .1, size = 1.5,
               var.order = "unadjusted",
               title = "Standardized Differences and Match 5") +
    theme_bw()
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-48-1.png)<!-- -->

## Rubin’s Rules 1 and 2 for Match 5

Create a new data frame, containing only the matched sample.

``` r
matches_5 <- factor(rep(match5$index.treated, 2))
rhc.matches_5 <- cbind(matches_5, 
          rhc[c(match5$index.control, match5$index.treated),])
```

Rubin Rule 1 result after matching should ideally be near 0, and
certainly between -50 and +50.

``` r
rubin1.m5 <- with(rhc.matches_5, 
                  abs(100*(mean(linps[swang1=="RHC"]) - 
                               mean(linps[swang1=="No RHC"]))/
                          sd(linps)))
rubin1.m5
```

    [1] 1.633545

Rubin Rule 2 result after matching should ideally be near 1, and
certainly between 1/2 and 2.

``` r
rubin2.m5 <- with(rhc.matches_5, 
                  var(linps[swang1 == "RHC"]) / 
                      var(linps[swang1 == "No RHC"]))
rubin2.m5
```

    [1] 1.026349

# Match 6: 1:2 Greedy Matching on the linear PS, WITH Replacement

``` r
Y <- rhc$hospdays
X <- rhc$linps
Tr <- as.logical(rhc$swang1 == "RHC")
match6 <- Match(Y = Y, Tr = Tr, X = X, M = 2, 
                estimand = "ATT", replace = TRUE, 
                ties = FALSE)
summary(match6)
```

``` 

Estimate...  1.4235 
SE.........  0.87008 
T-stat.....  1.6361 
p.val......  0.10182 

Original number of observations..............  5735 
Original number of treated obs...............  2184 
Matched number of observations...............  2184 
Matched number of observations  (unweighted).  4368 
```

## Love Plot for Match 6

``` r
b6 <- bal.tab(match6, 
              swang1 == "RHC"  ~ 
                  age + sex + edu + income + ninsclas + race +
                  cat1 + dnr1 + wtkilo1 + hrt1 + meanbp1 + 
                  resp1 + temp1 +
                  card + gastr + hema + meta + neuro + ortho + 
                  renal + resp + seps + trauma +
                  amihx + ca + cardiohx + chfhx + chrpulhx +
                  dementhx + gibledhx + immunhx + liverhx +
                  malighx + psychhx + renalhx + transhx +
                  aps1 + das2d3pc + scoma1 + surv2md1 +
                  alb1 + bili1 + crea1 + hema1 + paco21 + pafi1 +
                  ph1 + pot1 + sod1 + wblc1 + ps + linps,
              data=rhc, un = TRUE)

love.plot(b6, threshold = .1, size = 1.5,
               var.order = "unadjusted",
               title = "Standardized Differences and Match 6") +
    theme_bw()
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-53-1.png)<!-- -->

## Rubin’s Rules 1 and 2 for Match 6

Create a new data frame, containing only the matched sample.

``` r
matches_6 <- factor(rep(match6$index.treated, 2))
rhc.matches_6 <- cbind(matches_6, 
          rhc[c(match6$index.control, match6$index.treated),])
```

Rubin Rule 1 result after matching should ideally be near 0, and
certainly between -50 and +50.

``` r
rubin1.m6 <- with(rhc.matches_6, 
                  abs(100*(mean(linps[swang1=="RHC"]) - 
                               mean(linps[swang1=="No RHC"]))/
                          sd(linps)))
rubin1.m6
```

    [1] 0.1152546

Rubin Rule 2 result after matching should ideally be near 1, and
certainly between 1/2 and 2.

``` r
rubin2.m6 <- with(rhc.matches_6, 
                  var(linps[swang1 == "RHC"]) / 
                      var(linps[swang1 == "No RHC"]))
rubin2.m6
```

    [1] 1.005538

# Ranking the Matches

| Match | Rubin 1 | Rubin 2 | Love Plot | Matched Sets | Description                 |
| ----: | ------: | ------: | --------- | -----------: | --------------------------- |
|  None |   101.6 |    0.74 | Terrible  |            – | No Matching                 |
|     1 |    61.9 |    1.69 | Not Good  |        2,184 | 1:1 greedy w/o repl         |
|     2 |   101.2 |    0.76 | Terrible  |        1,775 | 1:2 greedy w/o repl         |
|     3 |       0 |       1 | Good      |        2,184 | Genetic Search 1:1 w/o repl |
|     4 |    61.9 |    1.69 | Not Good  |        2,184 | 1:1 greedy with repl        |
|     5 |     1.6 |    1.03 | Great     |        1,563 | 1:1 caliper with repl       |
|     6 |     0.1 |    1.01 | Good      |        2,184 | 1:2 greedy with repl        |

# ATT Matching Estimates for the Binary Outcome, Death

## With Match 1, in detail

Note that the variable which identifies the matches (called `matches_1`)
is set up as a factor, as it needs to be, and that I’m using the 1/0
versions of both the outcome (so `died` rather than `death`) and
treatment (so `treat_rhc` rather than
`swang1`).

``` r
death_adj_m1 <- clogit(died ~ treat_rhc + strata(matches_1), data = rhc.matches_1)

summary(death_adj_m1)
```

    Call:
    coxph(formula = Surv(rep(1, 4368L), died) ~ treat_rhc + strata(matches_1), 
        data = rhc.matches_1, method = "exact")
    
      n= 4368, number of events= 2861 
    
                 coef exp(coef) se(coef)    z Pr(>|z|)    
    treat_rhc 0.22774   1.25576  0.06434 3.54    4e-04 ***
    ---
    Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    
              exp(coef) exp(-coef) lower .95 upper .95
    treat_rhc     1.256     0.7963     1.107     1.425
    
    Concordance= 0.557  (se = 0.022 )
    Rsquare= 0.003   (max possible= 0.267 )
    Likelihood ratio test= 12.61  on 1 df,   p=4e-04
    Wald test            = 12.53  on 1 df,   p=4e-04
    Score (logrank) test = 12.59  on 1 df,   p=4e-04

The odds ratio in the `exp(coef)` section above is the average causal
effect estimate. It describes the odds of having an event (`died`) occur
associated with being a RHC subject (as identified by `treat_rhc`), as
compared to the odds of that event when a non-RHC subject. We can tidy
this with:

``` r
tidy(death_adj_m1, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic  p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.26    0.0643      3.54 0.000400     1.11      1.42

## With Matches 2-6, in much less detail

``` r
death_adj_m2 <- clogit(died ~ treat_rhc + strata(matches_2), data = rhc.matches_2)
tidy(death_adj_m2, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic     p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>       <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.34    0.0552      5.31 0.000000112     1.20      1.49

``` r
death_adj_m3 <- clogit(died ~ treat_rhc + strata(matches_3), data = rhc.matches_3)
tidy(death_adj_m3, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic    p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>      <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.33    0.0625      4.62 0.00000377     1.18      1.51

``` r
death_adj_m4 <- clogit(died ~ treat_rhc + strata(matches_4), data = rhc.matches_4)
tidy(death_adj_m4, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic  p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.27    0.0643      3.70 0.000218     1.12      1.44

``` r
death_adj_m5 <- clogit(died ~ treat_rhc + strata(matches_5), data = rhc.matches_5)
tidy(death_adj_m5, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic   p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.34    0.0747      3.90 0.0000946     1.16      1.55

``` r
death_adj_m6 <- clogit(died ~ treat_rhc + strata(matches_6), data = rhc.matches_6)
tidy(death_adj_m6, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic      p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>        <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.31    0.0496      5.39 0.0000000685     1.19      1.44

## Graphing the Results Across Multiple Matching Strategies

``` r
temp0 <- tidy(death_unadj, conf.int = TRUE, exponentiate = TRUE) %>% 
    filter(term == "treat_rhc")
temp1 <- tidy(death_adj_m1, exponentiate = TRUE, conf.level = 0.95)
temp2 <- tidy(death_adj_m2, exponentiate = TRUE, conf.level = 0.95)
temp3 <- tidy(death_adj_m3, exponentiate = TRUE, conf.level = 0.95)
temp4 <- tidy(death_adj_m4, exponentiate = TRUE, conf.level = 0.95)
temp5 <- tidy(death_adj_m5, exponentiate = TRUE, conf.level = 0.95)
temp6 <- tidy(death_adj_m6, exponentiate = TRUE, conf.level = 0.95)

death_match_results <- rbind(temp0, temp1, temp2, temp3, temp4, temp5, temp6)

death_match_results <- death_match_results %>%
    mutate(approach = c("Unmatched", "Match 1", "Match 2", "Match 3", "Match 4", "Match 5", "Match 6")) %>%
    mutate(description = c("No Matching", "1:1 greedy matching without replacement", 
                           "1:2 greedy matching without replacement",
                           "1:1 genetic search matching without replacement",
                           "1:1 greedy matching with replacement",
                           "1:1 caliper matching on the linear PS with replacement",
                           "1:2 greedy matching with replacement"))

death_match_results
```

    # A tibble: 7 x 9
      term  estimate std.error statistic p.value conf.low conf.high approach
      <chr>    <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl> <chr>   
    1 trea~     1.25    0.0576      3.90 9.43e-5     1.12      1.40 Unmatch~
    2 trea~     1.26    0.0643      3.54 4.00e-4     1.11      1.42 Match 1 
    3 trea~     1.34    0.0552      5.31 1.12e-7     1.20      1.49 Match 2 
    4 trea~     1.33    0.0625      4.62 3.77e-6     1.18      1.51 Match 3 
    5 trea~     1.27    0.0643      3.70 2.18e-4     1.12      1.44 Match 4 
    6 trea~     1.34    0.0747      3.90 9.46e-5     1.16      1.55 Match 5 
    7 trea~     1.31    0.0496      5.39 6.85e-8     1.19      1.44 Match 6 
    # ... with 1 more variable: description <chr>

``` r
ggplot(death_match_results, aes(x = approach, y = estimate, ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(label = round_half_up(estimate,2)), vjust = -1.25) +
    geom_pointrange() +
    geom_hline(yintercept = 1, col = "red", linetype = "dashed") +
    theme_bw() +
    coord_flip() +
    labs(title = "Comparing ATT Estimates for Death using RHC Propensity Matching",
         x = "Propensity Adjustment Approach", 
         y = "Estimated Odds Ratio for Death associated with RHC")
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-65-1.png)<!-- -->

Let’s look at just the three strategies that achieved stronger balance.

``` r
death_match_results %>%
    filter(approach %in% c("Match 3", "Match 5", "Match 6")) %>%
ggplot(., aes(x = description, y = estimate, ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(label = round_half_up(estimate,2)), vjust = -1.25) +
    geom_pointrange() +
    geom_hline(yintercept = 1, col = "red", linetype = "dashed") +
    theme_bw() +
    coord_flip() +
    labs(title = "ATT Matching Estimates in RHC (Death)",
         x = "Propensity Adjustment Approach", 
         y = "Estimated Odds Ratio for Death associated with RHC")
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-66-1.png)<!-- -->

# ATT Matching Estimates for the Quantitative Outcome, Hospital Length of Stay

## With Match 1, in detail

Again, the variable which identifies the matches (called `matches_1`) is
set up as a factor, as it needs to be, and that I’m using the 1/0
version of treatment (so `treat_rhc` rather than `swang1`).

Our result for this quantitative outcome (`hospdays`) comes from a mixed
model where the matches are treated as a random factor, but the
treatment group is treated as a fixed factor, using the `lme4` package.

``` r
hospdays_adj_m1 <- lmer(hospdays ~ treat_rhc + (1 | matches_1),
                        data = rhc.matches_1)
```

    boundary (singular) fit: see ?isSingular

``` r
summary(hospdays_adj_m1); confint(hospdays_adj_m1)
```

    Linear mixed model fit by REML ['lmerMod']
    Formula: hospdays ~ treat_rhc + (1 | matches_1)
       Data: rhc.matches_1
    
    REML criterion at convergence: 40949.9
    
    Scaled residuals: 
        Min      1Q  Median      3Q     Max 
    -0.8633 -0.5710 -0.3047  0.1899 12.0726 
    
    Random effects:
     Groups    Name        Variance Std.Dev.
     matches_1 (Intercept)   0.0     0.00   
     Residual              690.8    26.28   
    Number of obs: 4368, groups:  matches_1, 2184
    
    Fixed effects:
                Estimate Std. Error t value
    (Intercept)  21.0078     0.5624  37.353
    treat_rhc     3.6836     0.7954   4.631
    
    Correlation of Fixed Effects:
              (Intr)
    treat_rhc -0.707
    convergence code: 0
    boundary (singular) fit: see ?isSingular

    Computing profile confidence intervals ...

    Warning in zeta(shiftpar, start = opt[seqpar1][-w]): slightly lower
    deviances (diff=-7.27596e-12) detected

    Warning in nextpar(mat, cc, i, delta, lowcut, upcut): Last two rows have
    identical or NA .zeta values: using minstep
    
    Warning in nextpar(mat, cc, i, delta, lowcut, upcut): Last two rows have
    identical or NA .zeta values: using minstep
    
    Warning in nextpar(mat, cc, i, delta, lowcut, upcut): Last two rows have
    identical or NA .zeta values: using minstep
    
    Warning in nextpar(mat, cc, i, delta, lowcut, upcut): Last two rows have
    identical or NA .zeta values: using minstep

    Warning in zetafun(np, ns): slightly lower deviances (diff=-7.27596e-12)
    detected

    Warning in FUN(X[[i]], ...): non-monotonic profile for .sig01

    Warning in confint.thpr(pp, level = level, zeta = zeta): bad spline fit
    for .sig01: falling back to linear interpolation

``` 
                2.5 %    97.5 %
.sig01       0.000000  3.450961
.sigma      25.735825 26.838178
(Intercept) 19.905485 22.110082
treat_rhc    2.124723  5.242493
```

The estimated effect of `treat_rhc` in the fixed effects section,
combined with the 95% confidence intervals material, provides the
average causal effect estimate. It describes the change in the outcome
`hospdays` associated with being a RHC subject (as identified by
`treat_rhc`), as compared to being a non-RHC subject. We can tidy this
with:

``` r
tidy(hospdays_adj_m1, conf.int = TRUE, conf.level = 0.95)
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector

    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

    # A tibble: 4 x 7
      term              estimate std.error statistic conf.low conf.high group  
      <chr>                <dbl>     <dbl>     <dbl>    <dbl>     <dbl> <chr>  
    1 (Intercept)          21.0      0.562     37.4     19.9      22.1  fixed  
    2 treat_rhc             3.68     0.795      4.63     2.12      5.24 fixed  
    3 sd_(Intercept).m~     0       NA         NA       NA        NA    matche~
    4 sd_Observation.R~    26.3     NA         NA       NA        NA    Residu~

or more specifically, we can look at just the treatment effect with:

``` r
tidy(hospdays_adj_m1, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector

    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

    # A tibble: 1 x 7
      term      estimate std.error statistic conf.low conf.high group
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>     <dbl> <chr>
    1 treat_rhc     3.68     0.795      4.63     2.12      5.24 fixed

## With Matches 2-6, in much less detail

``` r
hospdays_adj_m2 <- lmer(hospdays ~ treat_rhc + (1 | matches_2),
                        data = rhc.matches_2)
tidy(hospdays_adj_m2, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector

    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

    # A tibble: 1 x 7
      term      estimate std.error statistic conf.low conf.high group
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>     <dbl> <chr>
    1 treat_rhc     4.98     0.549      9.07     3.90      6.06 fixed

``` r
hospdays_adj_m3 <- lmer(hospdays ~ treat_rhc + (1 | matches_3),
                        data = rhc.matches_3)
tidy(hospdays_adj_m3, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector

    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

    # A tibble: 1 x 7
      term      estimate std.error statistic conf.low conf.high group
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>     <dbl> <chr>
    1 treat_rhc     1.61     0.801      2.01   0.0438      3.19 fixed

``` r
hospdays_adj_m4 <- lmer(hospdays ~ treat_rhc + (1 | matches_4),
                        data = rhc.matches_4)
```

    boundary (singular) fit: see ?isSingular

``` r
tidy(hospdays_adj_m4, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector

    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

    # A tibble: 1 x 7
      term      estimate std.error statistic conf.low conf.high group
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>     <dbl> <chr>
    1 treat_rhc     3.65     0.796      4.58     2.09      5.21 fixed

``` r
hospdays_adj_m5 <- lmer(hospdays ~ treat_rhc + (1 | matches_5),
                        data = rhc.matches_5)
tidy(hospdays_adj_m5, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector

    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

    # A tibble: 1 x 7
      term      estimate std.error statistic conf.low conf.high group
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>     <dbl> <chr>
    1 treat_rhc     2.21     0.906      2.43    0.429      3.98 fixed

``` r
hospdays_adj_m6 <- lmer(hospdays ~ treat_rhc + (1 | matches_6),
                        data = rhc.matches_6)
tidy(hospdays_adj_m6, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector

    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

    # A tibble: 1 x 7
      term      estimate std.error statistic conf.low conf.high group
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>     <dbl> <chr>
    1 treat_rhc     1.42     0.564      2.53    0.319      2.53 fixed

## Graphing the Results Across Multiple Matching Strategies

``` r
temp0 <- tidy(hospdays_unadj, conf.int = TRUE) %>% 
    filter(term == "treat_rhc") %>% select(-p.value) %>%
    mutate(group = "fixed")

temp1 <- tidy(hospdays_adj_m1, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector

    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

``` r
temp2 <- tidy(hospdays_adj_m2, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector
    
    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

``` r
temp3 <- tidy(hospdays_adj_m3, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector
    
    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

``` r
temp4 <- tidy(hospdays_adj_m4, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector
    
    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

``` r
temp5 <- tidy(hospdays_adj_m5, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector
    
    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

``` r
temp6 <- tidy(hospdays_adj_m6, conf.int = TRUE, conf.level = 0.95) %>% 
    filter(term == "treat_rhc")
```

    Warning in bind_rows_(x, .id): binding factor and character vector,
    coercing into character vector
    
    Warning in bind_rows_(x, .id): binding character and factor vector,
    coercing into character vector

``` r
hospdays_match_results <- rbind(temp0, temp1, temp2, temp3, temp4, temp5, temp6)

hospdays_match_results <- hospdays_match_results %>%
    mutate(approach = c("Unmatched", "Match 1", "Match 2", "Match 3", "Match 4", "Match 5", "Match 6")) %>%
    mutate(description = c("No Matching", "1:1 greedy matching without replacement", 
                           "1:2 greedy matching without replacement",
                           "1:1 genetic search matching without replacement",
                           "1:1 greedy matching with replacement",
                           "1:1 caliper matching on the linear PS with replacement",
                           "1:2 greedy matching with replacement"))

hospdays_match_results
```

    # A tibble: 7 x 9
      term  estimate std.error statistic conf.low conf.high group approach
      <chr>    <dbl>     <dbl>     <dbl>    <dbl>     <dbl> <chr> <chr>   
    1 trea~     5.16     0.687      7.51   3.82        6.51 fixed Unmatch~
    2 trea~     3.68     0.795      4.63   2.12        5.24 fixed Match 1 
    3 trea~     4.98     0.549      9.07   3.90        6.06 fixed Match 2 
    4 trea~     1.61     0.801      2.01   0.0438      3.19 fixed Match 3 
    5 trea~     3.65     0.796      4.58   2.09        5.21 fixed Match 4 
    6 trea~     2.21     0.906      2.43   0.429       3.98 fixed Match 5 
    7 trea~     1.42     0.564      2.53   0.319       2.53 fixed Match 6 
    # ... with 1 more variable: description <chr>

``` r
ggplot(hospdays_match_results, aes(x = approach, y = estimate, ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(label = round_half_up(estimate,2)), vjust = -1.25) +
    geom_pointrange() +
    geom_hline(yintercept = 1, col = "red", linetype = "dashed") +
    theme_bw() +
    coord_flip() +
    labs(title = "Comparing ATT Estimates for LOS using RHC Propensity Matching",
         x = "Propensity Adjustment Approach", 
         y = "Estimated Change in Hospital Length of Stay associated with RHC")
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-76-1.png)<!-- -->

Let’s look at just the three strategies that achieved stronger balance.

``` r
hospdays_match_results %>%
    filter(approach %in% c("Match 3", "Match 5", "Match 6")) %>%
ggplot(., aes(x = description, y = estimate, ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(label = round_half_up(estimate,2)), vjust = -1.25) +
    geom_pointrange() +
    geom_hline(yintercept = 1, col = "red", linetype = "dashed") +
    theme_bw() +
    coord_flip() +
    labs(title = "ATT Matching Estimates in RHC (LOS)",
         x = "Propensity Adjustment Approach", 
         y = "Est. Change in Hospital LOS associated with RHC")
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-77-1.png)<!-- -->

# ATT Matching Estimates for the Time-to-Event Outcome, In-Study Survival

We’ll use a stratified Cox proportional hazards model to compare the
RHC/No RHC groups on our time-to-event outcome `survdays`, while
accounting for the matched pairs. The main result will be a relative
hazard rate estimate, with 95% CI. I will use the 0/1 numeric versions
of the event indicator (`died`), and of the treatment indicator
(`treat_rhc`).

## With Match 1, in detail

``` r
survdays_adj_m1 <- coxph(Surv(survdays, died) ~ treat_rhc + strata(matches_1), data=rhc.matches_1)
summary(survdays_adj_m1)
```

    Call:
    coxph(formula = Surv(survdays, died) ~ treat_rhc + strata(matches_1), 
        data = rhc.matches_1)
    
      n= 4368, number of events= 2861 
    
                 coef exp(coef) se(coef)     z Pr(>|z|)  
    treat_rhc 0.07549   1.07841  0.04550 1.659   0.0971 .
    ---
    Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    
              exp(coef) exp(-coef) lower .95 upper .95
    treat_rhc     1.078     0.9273    0.9864     1.179
    
    Concordance= 0.519  (se = 0.016 )
    Rsquare= 0.001   (max possible= 0.456 )
    Likelihood ratio test= 2.75  on 1 df,   p=0.1
    Wald test            = 2.75  on 1 df,   p=0.1
    Score (logrank) test = 2.75  on 1 df,   p=0.1

The hazard ratio in the `exp(coef)` section is the average causal effect
estimate. It describes the hazard for having an event (`died`) occur
associated with being a RHC subject (as identified by `treat_rhc`), as
compared to the hazard of that event when a non-RHC subject. We can tidy
this with:

``` r
tidy(survdays_adj_m1, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.08    0.0455      1.66  0.0971    0.986      1.18

## With Matches 2-6, in much less detail

``` r
survdays_adj_m2 <- coxph(Surv(survdays, died) ~ treat_rhc + strata(matches_2), data=rhc.matches_2)
tidy(survdays_adj_m2, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic  p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.28    0.0344      7.26 3.86e-13     1.20      1.37

``` r
survdays_adj_m3 <- coxph(Surv(survdays, died) ~ treat_rhc + strata(matches_3), data=rhc.matches_3)
tidy(survdays_adj_m3, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.13    0.0434      2.90 0.00375     1.04      1.23

``` r
survdays_adj_m4 <- coxph(Surv(survdays, died) ~ treat_rhc + strata(matches_4), data=rhc.matches_4)
tidy(survdays_adj_m4, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.11    0.0455      2.21  0.0274     1.01      1.21

``` r
survdays_adj_m5 <- coxph(Surv(survdays, died) ~ treat_rhc + strata(matches_5), data=rhc.matches_5)
tidy(survdays_adj_m5, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.13    0.0534      2.21  0.0271     1.01      1.25

``` r
survdays_adj_m6 <- coxph(Surv(survdays, died) ~ treat_rhc + strata(matches_6), data=rhc.matches_6)
tidy(survdays_adj_m6, exponentiate = TRUE, conf.level = 0.95)
```

    # A tibble: 1 x 7
      term      estimate std.error statistic  p.value conf.low conf.high
      <chr>        <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    1 treat_rhc     1.31    0.0312      8.70 3.24e-18     1.23      1.39

## Graphing the Results Across Multiple Matching Strategies

``` r
temp0 <- tidy(survdays_unadj, conf.int = TRUE, exponentiate = TRUE)

temp1 <- tidy(survdays_adj_m1, exponentiate = TRUE, conf.level = 0.95)

temp2 <- tidy(survdays_adj_m2, exponentiate = TRUE, conf.level = 0.95)

temp3 <- tidy(survdays_adj_m3, exponentiate = TRUE, conf.level = 0.95)

temp4 <- tidy(survdays_adj_m4, exponentiate = TRUE, conf.level = 0.95)

temp5 <- tidy(survdays_adj_m5, exponentiate = TRUE, conf.level = 0.95)

temp6 <- tidy(survdays_adj_m6, exponentiate = TRUE, conf.level = 0.95)


survdays_match_results <- rbind(temp0, temp1, temp2, temp3, temp4, temp5, temp6)

survdays_match_results <- survdays_match_results %>%
    mutate(approach = c("Unmatched", "Match 1", "Match 2", "Match 3", "Match 4", "Match 5", "Match 6")) %>%
    mutate(description = c("No Matching", "1:1 greedy matching without replacement", 
                           "1:2 greedy matching without replacement",
                           "1:1 genetic search matching without replacement",
                           "1:1 greedy matching with replacement",
                           "1:1 caliper matching on the linear PS with replacement",
                           "1:2 greedy matching with replacement"))

survdays_match_results
```

    # A tibble: 7 x 9
      term  estimate std.error statistic  p.value conf.low conf.high approach
      <chr>    <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl> <chr>   
    1 trea~     1.08    0.0335      2.34 1.92e- 2    1.01       1.15 Unmatch~
    2 trea~     1.08    0.0455      1.66 9.71e- 2    0.986      1.18 Match 1 
    3 trea~     1.28    0.0344      7.26 3.86e-13    1.20       1.37 Match 2 
    4 trea~     1.13    0.0434      2.90 3.75e- 3    1.04       1.23 Match 3 
    5 trea~     1.11    0.0455      2.21 2.74e- 2    1.01       1.21 Match 4 
    6 trea~     1.13    0.0534      2.21 2.71e- 2    1.01       1.25 Match 5 
    7 trea~     1.31    0.0312      8.70 3.24e-18    1.23       1.39 Match 6 
    # ... with 1 more variable: description <chr>

``` r
ggplot(survdays_match_results, aes(x = approach, y = estimate, ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(label = round_half_up(estimate,2)), vjust = -1.25) +
    geom_pointrange() +
    geom_hline(yintercept = 1, col = "red", linetype = "dashed") +
    theme_bw() +
    coord_flip() +
    labs(title = "Comparing ATT Estimates for Survival using RHC Propensity Matching",
         x = "Propensity Adjustment Approach", 
         y = "Estimated Hazard Ratio associated with RHC")
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-86-1.png)<!-- -->

Let’s look at just the three strategies that achieved stronger balance.

``` r
survdays_match_results %>%
    filter(approach %in% c("Match 3", "Match 5", "Match 6")) %>%
ggplot(., aes(x = description, y = estimate, ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(label = round_half_up(estimate,2)), vjust = -1.25) +
    geom_pointrange() +
    geom_hline(yintercept = 1, col = "red", linetype = "dashed") +
    theme_bw() +
    coord_flip() +
    labs(title = "ATT Matching Estimates in RHC (Survival)",
         x = "Propensity Adjustment Approach", 
         y = "Estimated Hazard Ratio associated with RHC")
```

![](01_rhc_2019_files/figure-gfm/unnamed-chunk-87-1.png)<!-- -->

# Sensitivity Analyses

## For the Binary Outcome, Death

The `rbounds` package can evaluate binary outcomes using the
`binarysens` and `Fishersens` functions. The `binarysens` function works
directly on a matched sample as developed using the Matching package.
For example, in our third match, based on the genetic search algorithm
with 1:1 matching without replacement, this is `match3`.

``` r
binarysens(match3, Gamma = 2, GammaInc = 0.1)
```

``` 

 Rosenbaum Sensitivity Test 
 
Unconfounded estimate ....  0.0312 

 Gamma Lower bound Upper bound
   1.0     0.03125     0.03125
   1.1     0.02449     0.03943
   1.2     0.01940     0.04828
   1.3     0.01554     0.05769
   1.4     0.01256     0.06754
   1.5     0.01024     0.07776
   1.6     0.00842     0.08825
   1.7     0.00697     0.09895
   1.8     0.00581     0.10979
   1.9     0.00488     0.12072
   2.0     0.00412     0.13169

 Note: Gamma is Odds of Differential Assignment To
 Treatment Due to Unobserved Factors 
 
```

At a 5% significance level, we retain significance up to a hidden bias
of \(\Gamma\) = 1.2, but not at \(\Gamma\) = 1.3. See the `toy_2019`
example discussed in Class 4, as well as Chapter 9 of Rosenbaum’s
*Observation and Experiment* for more details on interpretation of this
result.

We can also use this approach with other Matching results, including
Match 6, which is a 1:2 match with replacement.

``` r
binarysens(match6, Gamma = 3, GammaInc = 0.25)
```

``` 

 Rosenbaum Sensitivity Test 
 
Unconfounded estimate ....  0.0327 

 Gamma Lower bound Upper bound
  1.00     0.03271     0.03271
  1.25     0.01346     0.07002
  1.50     0.00592     0.11892
  1.75     0.00277     0.17496
  2.00     0.00137     0.23411
  2.25     0.00071     0.29335
  2.50     0.00039     0.35065
  2.75     0.00022     0.40482
  3.00     0.00013     0.45520

 Note: Gamma is Odds of Differential Assignment To
 Treatment Due to Unobserved Factors 
 
```

Here, at a 5% significance level, we retain significance up to a hidden
bias of \(\Gamma\) = 2.5, but not at \(\Gamma\) = 2.75.

## For the Quantitative Outcome, In-Hospital Length of Stay

We have already used the `Match` function from the Matching package to
develop our matched samples. For our 1:1 matches, we need only run the
`psens` function from the `rbounds` package to obtain sensitivity
results. For example, in Match 3,

``` r
psens(match3, Gamma = 1.5, GammaInc = 0.1)
```

``` 

 Rosenbaum Sensitivity Test for Wilcoxon Signed Rank P-Value 
 
Unconfounded estimate ....  1e-04 

 Gamma Lower bound Upper bound
   1.0       1e-04      0.0001
   1.1       0e+00      0.0358
   1.2       0e+00      0.5008
   1.3       0e+00      0.9517
   1.4       0e+00      0.9993
   1.5       0e+00      1.0000

 Note: Gamma is Odds of Differential Assignment To
 Treatment Due to Unobserved Factors 
 
```

At a 5% significance level, we retain significance up to a hidden bias
of \(\Gamma\) = 1.1, but not at \(\Gamma\) = 1.2. See the `toy_2019`
example discussed in Class 4, as well as Chapter 9 of Rosenbaum’s
*Observation and Experiment* for more details on interpretation of this
result.

For a matching with more than 1 control, we need to apply the `mcontrol`
function, which requires the use of the `data.prep` function from
`rbounds`. So, for example, in Match 6, which is a 1:2 greedy match (so
that each matched set has 3 patients in it, making the `group.size` =
3), we would have:

``` r
tmp <- data.prep(match6, group.size = 3)

mcontrol(tmp$Y, tmp$id, tmp$treat, group.size=3, Gamma = 1.5, GammaInc = 0.1)
```

``` 

 Rosenbaum Sensitivity Test for Wilcoxon Strat. Rank P-Value 
 
Unconfounded estimate ....  0 

 Gamma Lower bound Upper bound
   1.0           0      0.0000
   1.1           0      0.0163
   1.2           0      0.3386
   1.3           0      0.8773
   1.4           0      0.9956
   1.5           0      1.0000

 Note: Gamma is Odds of Differential Assignment To
 Treatment Due to Unobserved Factors 
 
```

Again, at a 5% significance level, we retain significance up to a hidden
bias of \(\Gamma\) = 1.1, but not at \(\Gamma\) = 1.2.

## For the Survival Outcome, In-Study Time to Death

In this setting, we would need to use the spreadsheet software provided
by Dr. Love. That software is designed only for 1:1 greedy matching
without replacement or weighting, which is the approach we took in Match
1. We need to identify, for each matched pair of subjects, whether that
pair’s set of results was:

  - that the RHC patient definitely survived longer than the non-RHC
    patient
  - that the non-RHC patient definitely survived longer than the RHC
    patient
  - that it is unclear which patient survived longer, due to censoring

Here is some very fussy code that accomplishes this counting. This could
probably be accomplished just as well with some sort of `case_when`
statement, but it’s a bit tricky.

``` r
a1 <- rhc.matches_1 %>% 
    select(matches_1, swang1, death, survdays) %>%
    arrange(matches_1) 
```

``` r
a2 <- unite(a1, situation, swang1, death, sep = "_", remove = TRUE)

a3 <- spread(a2, situation, survdays)

a4 <- a3 %>%
    filter(complete.cases(`No RHC_Yes`, `RHC_Yes`)) %>%
    mutate(result = ifelse(`RHC_Yes` > `No RHC_Yes`, "RHC lived longer", "No RHC lived longer"))

a5 <- a3 %>%
    filter(complete.cases(`No RHC_No`, `RHC_No`)) %>%
    mutate(result = "No clear winner")

a6 <- a3 %>%
    filter(complete.cases(`No RHC_No`, `RHC_Yes`)) %>%
    mutate(result = ifelse(`RHC_Yes` > `No RHC_No`, "No clear winner", "No RHC lived longer"))

a7 <- a3 %>%
    filter(complete.cases(`No RHC_Yes`, `RHC_No`)) %>%
    mutate(result = ifelse(`RHC_No` > `No RHC_Yes`, "RHC lived longer", "No clear winner"))

a8 <- bind_rows(a4, a5, a6, a7)

a8 %>% tabyl(result) %>% adorn_totals()
```

``` 
              result    n   percent
     No clear winner  268 0.1227106
 No RHC lived longer 1004 0.4597070
    RHC lived longer  912 0.4175824
               Total 2184 1.0000000
```

So we have counts for the pairs where a clear winner is identified, and
we can enter the spreadsheet. We need the number of pairs with a clear
winner, and the number of pairs where the No RHC patient lived longer
than the RHC
    patient.

# Session Info

``` r
sessioninfo::session_info()
```

    - Session info ----------------------------------------------------------
     setting  value                       
     version  R version 3.5.3 (2019-03-11)
     os       Windows 10 x64              
     system   x86_64, mingw32             
     ui       RTerm                       
     language (EN)                        
     collate  English_United States.1252  
     ctype    English_United States.1252  
     tz       America/New_York            
     date     2019-03-14                  
    
    - Packages --------------------------------------------------------------
     package     * version  date       lib source        
     assertthat    0.2.0    2017-04-11 [1] CRAN (R 3.5.0)
     backports     1.1.3    2018-12-14 [1] CRAN (R 3.5.2)
     boot          1.3-20   2017-08-06 [1] CRAN (R 3.5.2)
     broom       * 0.5.1    2018-12-05 [1] CRAN (R 3.5.2)
     cellranger    1.1.0    2016-07-27 [1] CRAN (R 3.5.0)
     class         7.3-15   2019-01-01 [2] CRAN (R 3.5.3)
     cli           1.0.1    2018-09-25 [1] CRAN (R 3.5.1)
     cobalt      * 3.6.1    2019-01-16 [1] CRAN (R 3.5.2)
     colorspace    1.4-0    2019-01-13 [1] CRAN (R 3.5.2)
     crayon        1.3.4    2017-09-16 [1] CRAN (R 3.5.0)
     crosstalk     1.0.0    2016-12-21 [1] CRAN (R 3.5.0)
     curl          3.3      2019-01-10 [1] CRAN (R 3.5.2)
     digest        0.6.18   2018-10-10 [1] CRAN (R 3.5.1)
     dplyr       * 0.8.0.1  2019-02-15 [1] CRAN (R 3.5.3)
     e1071         1.7-0.1  2019-01-21 [1] CRAN (R 3.5.2)
     evaluate      0.13     2019-02-12 [1] CRAN (R 3.5.3)
     fansi         0.4.0    2018-10-05 [1] CRAN (R 3.5.1)
     forcats     * 0.4.0    2019-02-17 [1] CRAN (R 3.5.3)
     generics      0.0.2    2018-11-29 [1] CRAN (R 3.5.1)
     ggdendro      0.1-20   2016-04-27 [1] CRAN (R 3.5.0)
     ggformula     0.9.1    2019-01-12 [1] CRAN (R 3.5.2)
     ggplot2     * 3.1.0    2018-10-25 [1] CRAN (R 3.5.1)
     ggrepel       0.8.0    2018-05-09 [1] CRAN (R 3.5.2)
     ggstance      0.3.1    2018-07-20 [1] CRAN (R 3.5.1)
     glue          1.3.1    2019-03-12 [1] CRAN (R 3.5.3)
     gridExtra     2.3      2017-09-09 [1] CRAN (R 3.5.2)
     gtable        0.2.0    2016-02-26 [1] CRAN (R 3.5.0)
     haven         2.1.0    2019-02-19 [1] CRAN (R 3.5.3)
     here        * 0.1      2017-05-28 [1] CRAN (R 3.5.2)
     hms           0.4.2    2018-03-10 [1] CRAN (R 3.5.0)
     htmltools     0.3.6    2017-04-28 [1] CRAN (R 3.5.0)
     htmlwidgets   1.3      2018-09-30 [1] CRAN (R 3.5.1)
     httpuv        1.4.5.1  2018-12-18 [1] CRAN (R 3.5.2)
     httr          1.4.0    2018-12-11 [1] CRAN (R 3.5.2)
     janitor     * 1.1.1    2018-07-31 [1] CRAN (R 3.5.1)
     jsonlite      1.6      2018-12-07 [1] CRAN (R 3.5.2)
     knitr         1.22     2019-03-08 [1] CRAN (R 3.5.3)
     labeling      0.3      2014-08-23 [1] CRAN (R 3.5.0)
     labelled      2.1.0    2019-02-25 [1] CRAN (R 3.5.3)
     later         0.8.0    2019-02-11 [1] CRAN (R 3.5.3)
     lattice       0.20-38  2018-11-04 [1] CRAN (R 3.5.2)
     lazyeval      0.2.1    2017-10-29 [1] CRAN (R 3.5.0)
     leaflet       2.0.2    2018-08-27 [1] CRAN (R 3.5.2)
     lme4        * 1.1-21   2019-03-05 [1] CRAN (R 3.5.3)
     lubridate     1.7.4    2018-04-11 [1] CRAN (R 3.5.0)
     magrittr      1.5      2014-11-22 [1] CRAN (R 3.5.2)
     MASS        * 7.3-51.1 2018-11-01 [1] CRAN (R 3.5.2)
     Matching    * 4.9-5    2019-03-07 [1] CRAN (R 3.5.3)
     Matrix      * 1.2-15   2018-11-01 [2] CRAN (R 3.5.3)
     mime          0.6      2018-10-05 [1] CRAN (R 3.5.1)
     minqa         1.2.4    2014-10-09 [1] CRAN (R 3.5.0)
     modelr        0.1.4    2019-02-18 [1] CRAN (R 3.5.3)
     mosaic        1.5.0    2019-01-12 [1] CRAN (R 3.5.2)
     mosaicCore    0.6.0    2018-06-24 [1] CRAN (R 3.5.0)
     mosaicData    0.17.0   2018-06-23 [1] CRAN (R 3.5.0)
     munsell       0.5.0    2018-06-12 [1] CRAN (R 3.5.0)
     naniar      * 0.4.2    2019-02-15 [1] CRAN (R 3.5.2)
     nlme          3.1-137  2018-04-07 [2] CRAN (R 3.5.3)
     nloptr        1.2.1    2018-10-03 [1] CRAN (R 3.5.1)
     pillar        1.3.1    2018-12-15 [1] CRAN (R 3.5.2)
     pkgconfig     2.0.2    2018-08-16 [1] CRAN (R 3.5.1)
     plyr          1.8.4    2016-06-08 [1] CRAN (R 3.5.0)
     promises      1.0.1    2018-04-13 [1] CRAN (R 3.5.0)
     purrr       * 0.3.1    2019-03-03 [1] CRAN (R 3.5.3)
     R6            2.4.0    2019-02-14 [1] CRAN (R 3.5.3)
     rbounds     * 2.1      2014-12-08 [1] CRAN (R 3.5.2)
     Rcpp          1.0.0    2018-11-07 [1] CRAN (R 3.5.1)
     readr       * 1.3.1    2018-12-21 [1] CRAN (R 3.5.2)
     readxl        1.3.1    2019-03-13 [1] CRAN (R 3.5.3)
     rgenoud     * 5.8-3.0  2019-01-24 [1] CRAN (R 3.5.2)
     rlang         0.3.1    2019-01-08 [1] CRAN (R 3.5.2)
     rmarkdown     1.12     2019-03-14 [1] CRAN (R 3.5.3)
     rprojroot     1.3-2    2018-01-03 [1] CRAN (R 3.5.0)
     rstudioapi    0.9.0    2019-01-09 [1] CRAN (R 3.5.2)
     rvest         0.3.2    2016-06-17 [1] CRAN (R 3.5.0)
     scales        1.0.0    2018-08-09 [1] CRAN (R 3.5.1)
     sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.5.1)
     shiny         1.2.0    2018-11-02 [1] CRAN (R 3.5.1)
     stringi       1.4.3    2019-03-12 [1] CRAN (R 3.5.3)
     stringr     * 1.4.0    2019-02-10 [1] CRAN (R 3.5.3)
     survey        3.35-1   2019-01-29 [1] CRAN (R 3.5.3)
     survival    * 2.43-3   2018-11-26 [1] CRAN (R 3.5.2)
     tableone    * 0.10.0   2019-02-17 [1] CRAN (R 3.5.3)
     tibble      * 2.0.1    2019-01-12 [1] CRAN (R 3.5.2)
     tidyr       * 0.8.3    2019-03-01 [1] CRAN (R 3.5.3)
     tidyselect    0.2.5    2018-10-11 [1] CRAN (R 3.5.1)
     tidyverse   * 1.2.1    2017-11-14 [1] CRAN (R 3.5.2)
     utf8          1.1.4    2018-05-24 [1] CRAN (R 3.5.0)
     viridisLite   0.3.0    2018-02-01 [1] CRAN (R 3.5.0)
     visdat        0.5.3    2019-02-15 [1] CRAN (R 3.5.2)
     withr         2.1.2    2018-03-15 [1] CRAN (R 3.5.0)
     xfun          0.5      2019-02-20 [1] CRAN (R 3.5.3)
     xml2          1.2.0    2018-01-24 [1] CRAN (R 3.5.0)
     xtable        1.8-3    2018-08-29 [1] CRAN (R 3.5.1)
     yaml          2.2.0    2018-07-25 [1] CRAN (R 3.5.1)
     zoo           1.8-4    2018-09-19 [1] CRAN (R 3.5.1)
    
    [1] C:/Users/Thomas/Documents/R/win-library/3.5
    [2] C:/Program Files/R/R-3.5.3/library
